/* eslint-disable */
// @ts-nocheck
/**
 * PDF &amp; DWG Exporter
 *
 * Generated by scripts/build-cards.mjs — do not edit. Both halves come out of
 * the design verbatim: `markup` is its stage, and `values` is its own
 * renderVals, untouched apart from taking the clock as an argument instead of
 * reading it off a component. See the script for the few things it adjusts.
 */

export const id = "acad-arch-pdf-dwg-exporter";
export const title = "PDF &amp; DWG Exporter";
export const width = 476;
export const height = 356;
export const loopMs = 15000;

/**
 * The attributes this card drives, as the design lists them.
 *
 * Each bound node carries data-bind-<attr> holding a template like "[[wx]]",
 * which the scene fills from the frame's values.
 */
export const attrs = [];

/** The stage's own styles, off the design's root element. */
export const stage = {
  "width": "476px",
  "height": "356px",
  "boxSizing": "border-box",
  "padding": "30px 48px 36px 48px",
  "display": "flex",
  "backgroundColor": "#FFFFFF",
  "color": "#16181C",
  "overflow": "hidden",
};

export const markup = `
<div style="width: 380px; flex-shrink: 0; height: 290px; display: flex; flex-direction: column; justify-content: flex-start; gap: 18px; padding-top: 4px;">
<h1 style="margin: 0; font-family: Archivo, 'Archivo Narrow', 'Arial Narrow', 'Helvetica Neue Condensed', 'Liberation Sans Narrow', Arial, sans-serif; font-stretch: 82%; font-weight: 800; font-size: 26px; line-height: 1.0; letter-spacing: -0.6px; color: #172B4D; min-height: 56px;"><span style="white-space: nowrap;">PDF &amp; DWG Exporter</span><br/><span style="color: #F28C28; white-space: nowrap;">Automation</span></h1>
<h2 style="margin: 0; font-family: Archivo, 'Archivo Narrow', 'Arial Narrow', 'Helvetica Neue Condensed', 'Liberation Sans Narrow', Arial, sans-serif; font-stretch: 88%; font-weight: 600; font-size: 22px; line-height: 1.2; color: #5A626E;">Hundreds of CAD layouts batch-exported to standard PDF and DWG.</h2>

<div style="height: 48px; flex-shrink: 0; display: flex; align-items: center; justify-content: flex-start; gap: 22px; margin-top: auto;"><div style="display: flex; align-items: center; gap: 14px;"><div style="font-size: 15px; font-weight: 600; letter-spacing: -0.1px; color: #16181C; white-space: nowrap;">Add-in for</div><div style="width: 1px; height: 30px; background: #D5D9DF;"></div><img src="/logos/autocad.png" alt="Autodesk AutoCAD" width="34" height="34" style="display: block; width: 34px; height: 34px; object-fit: contain;"></div><a href="#demo" style="display: inline-flex; align-items: center; height: 44px; padding: 0 22px; border-radius: 6px; background: #F28C28; color: #FFFFFF; font-weight: 600; font-size: 15px; text-decoration: none;">Book a demo</a></div></div>
`;

/** Everything the markup binds to, for one position in the loop. */
export function values(p) {
  // p is the argument.
  function lin(k) {
    if (p <= k[0][0]) return k[0][1];
    for (var i = 1; i < k.length; i++) if (p <= k[i][0]) { var a = k[i-1], b = k[i], f = (p - a[0]) / (b[0] - a[0]); f = 1 - Math.pow(1 - f, 3); return a[1] + (b[1] - a[1]) * f; }
    return k[k.length-1][1];
  }
  var out = p < 94 ? 1 : Math.max(0, 1 - (p - 94) / 6);
  var v = {};
  function phases(ph) { for (var i = 0; i < ph.length; i++) { v['on'+i] = (p >= ph[i][0] && p < ph[i][1]) ? 1 : 0; v['done'+i] = (p >= ph[i][1] && p < 97) ? out : 0; } }

  phases([[0,16],[16,32],[32,72],[72,82]]);
  var np = 0, nd = 0;
  for (var i = 0; i < 12; i++) {
    var a = lin([[2 + i * 0.8, 0],[4 + i * 0.8, 1]]);
    var t = 34 + i * 3, f = lin([[t,0],[t+2.5,1]]);
    var tx = (268 - (18 + (i % 4) * 62)) * f, ty = ((i % 2 ? 150 : 40) - (16 + Math.floor(i / 4) * 74)) * f;
    v['sh'+i] = 'opacity: ' + (a * (1 - 0.85 * f) * out).toFixed(3) + '; transform: translate(' + tx.toFixed(1) + 'px,' + ty.toFixed(1) + 'px) scale(' + (1 - 0.4 * f).toFixed(3) + ');';
    if (p >= t + 2.5) { np++; nd++; }
  }
  v.np = np; v.nd = nd;
  v.oO = lin([[30,0],[34,1]]) * out;
  v.k0 = p >= 10 ? out : 0.25 * out; v.k1 = p >= 18 ? out : 0.25 * out; v.k2 = p >= 24 ? out : 0.25 * out; v.k3 = p >= 30 ? out : 0.25 * out;
  v.fin = (p >= 74 && p < 97) ? out : 0;

  return { v: v };}

const card = { id, title, width, height, loopMs, attrs, stage, markup, values };
export default card;
