/* eslint-disable */
// @ts-nocheck
/**
 * Viewport &amp; Scale Automation
 *
 * Generated by scripts/build-cards.mjs — do not edit. Both halves come out of
 * the design verbatim: `markup` is its stage, and `values` is its own
 * renderVals, untouched apart from taking the clock as an argument instead of
 * reading it off a component. See the script for the few things it adjusts.
 */

export const id = "acad-mep-viewport-scale";
export const title = "Viewport &amp; Scale Automation";
export const width = 476;
export const height = 356;
export const loopMs = 15000;

/**
 * The attributes this card drives, as the design lists them.
 *
 * Each bound node carries data-bind-<attr> holding a template like "[[wx]]",
 * which the scene fills from the frame's values.
 */
export const attrs = ["fill","stroke"];

/** The stage's own styles, off the design's root element. */
export const stage = {
  "width": "476px",
  "height": "356px",
  "boxSizing": "border-box",
  "padding": "30px 48px 36px 48px",
  "display": "flex",
  "backgroundColor": "#FFFFFF",
  "color": "#16181C",
  "overflow": "hidden",
};

export const markup = `
<div style="width: 380px; flex-shrink: 0; height: 290px; display: flex; flex-direction: column; justify-content: flex-start; gap: 18px; padding-top: 4px;">
<h1 style="margin: 0; font-family: Archivo, 'Archivo Narrow', 'Arial Narrow', 'Helvetica Neue Condensed', 'Liberation Sans Narrow', Arial, sans-serif; font-stretch: 82%; font-weight: 800; font-size: 47px; line-height: 1.0; letter-spacing: -0.6px; color: #172B4D; min-height: 104px;"><span style="white-space: nowrap;">Viewport &amp; Scale</span><br/><span style="color: #F28C28; white-space: nowrap;">Automation</span></h1>
<h2 style="margin: 0; font-family: Archivo, 'Archivo Narrow', 'Arial Narrow', 'Helvetica Neue Condensed', 'Liberation Sans Narrow', Arial, sans-serif; font-stretch: 88%; font-weight: 600; font-size: 22px; line-height: 1.2; color: #5A626E;">Viewport scales, orientation and positions made consistent.</h2>

<div style="height: 48px; flex-shrink: 0; display: flex; align-items: center; justify-content: flex-start; gap: 22px; margin-top: auto;"><div style="display: flex; align-items: center; gap: 14px;"><div style="font-size: 15px; font-weight: 600; letter-spacing: -0.1px; color: #16181C; white-space: nowrap;">Add-in for</div><div style="width: 1px; height: 30px; background: #D5D9DF;"></div><img src="/logos/autocad.png" alt="Autodesk AutoCAD" width="34" height="34" style="display: block; width: 34px; height: 34px; object-fit: contain;"></div><a href="#demo" style="display: inline-flex; align-items: center; height: 44px; padding: 0 22px; border-radius: 6px; background: #F28C28; color: #FFFFFF; font-weight: 600; font-size: 15px; text-decoration: none;">Book a demo</a></div></div>
`;

/** Everything the markup binds to, for one position in the loop. */
export function values(p) {
  // p is the argument.
  function lin(k) {
    if (p <= k[0][0]) return k[0][1];
    for (var i = 1; i < k.length; i++) if (p <= k[i][0]) { var a = k[i-1], b = k[i], f = (p - a[0]) / (b[0] - a[0]); f = 1 - Math.pow(1 - f, 3); return a[1] + (b[1] - a[1]) * f; }
    return k[k.length-1][1];
  }
  var out = p < 94 ? 1 : Math.max(0, 1 - (p - 94) / 6);
  var v = {};
  function phases(ph) { for (var i = 0; i < ph.length; i++) { v['on'+i] = (p >= ph[i][0] && p < ph[i][1]) ? 1 : 0; v['done'+i] = (p >= ph[i][1] && p < 97) ? out : 0; } }

  var C = [[16, 20, 0.8, 8, 6], [138, 20, 1.15, -6, -4], [16, 148, 0.95, 4, 0], [138, 148, 1.0, 0, -8]];
  phases([[0,14],[14,34],[34,56],[56,80]]);
  var s = lin([[16,0],[28,1]]), r = lin([[36,0],[44,1]]), m = lin([[46,0],[54,1]]);
  var labels = ['1:125', '1:75', '1:110', '1:100'];
  for (var i = 0; i < 4; i++) {
    var c = C[i], cx = c[0] + 56, cy = c[1] + 47;
    var sc = c[2] + (1 - c[2]) * s, rot = c[4] * (1 - r), dx = c[3] * (1 - m);
    v['vp'+i] = 'transform: translate(' + dx.toFixed(1) + 'px,0px) rotate(' + rot.toFixed(1) + 'deg) scale(' + sc.toFixed(3) + '); transform-origin: ' + cx + 'px ' + cy + 'px;';
    var ok = s > 0.95 && r > 0.95 && m > 0.95;
    v['vc'+i] = ok ? '#1E7F4F' : (i == 3 && s > 0.95 ? '#1E7F4F' : '#C0392B');
    v['st'+i] = s > 0.95 ? '1:100' : labels[i]; v['sc'+i] = s > 0.95 ? '#1E7F4F' : '#B42318';
  }
  v.k0 = p >= 28 ? out : 0.25 * out; v.k1 = p >= 44 ? out : 0.25 * out; v.k2 = p >= 54 ? out : 0.25 * out; v.k3 = p >= 60 ? out : 0.25 * out; v.k4 = p >= 66 ? out : 0.25 * out;
  v.fin = (p >= 72 && p < 97) ? out : 0;

  return { v: v };}

const card = { id, title, width, height, loopMs, attrs, stage, markup, values };
export default card;
