/* eslint-disable */
// @ts-nocheck
/**
 * Auto Dimensioning &amp; Tagging
 *
 * Generated by scripts/build-cards.mjs — do not edit. Both halves come out of
 * the design verbatim: `markup` is its stage, and `values` is its own
 * renderVals, untouched apart from taking the clock as an argument instead of
 * reading it off a component. See the script for the few things it adjusts.
 */

export const id = "acad-mep-auto-dimensioning-tagging";
export const title = "Auto Dimensioning &amp; Tagging";
export const width = 476;
export const height = 356;
export const loopMs = 15000;

/**
 * The attributes this card drives, as the design lists them.
 *
 * Each bound node carries data-bind-<attr> holding a template like "[[wx]]",
 * which the scene fills from the frame's values.
 */
export const attrs = [];

/** The stage's own styles, off the design's root element. */
export const stage = {
  "width": "476px",
  "height": "356px",
  "boxSizing": "border-box",
  "padding": "30px 48px 36px 48px",
  "display": "flex",
  "backgroundColor": "#FFFFFF",
  "color": "#16181C",
  "overflow": "hidden",
};

export const markup = `
<div style="width: 380px; flex-shrink: 0; height: 290px; display: flex; flex-direction: column; justify-content: flex-start; gap: 18px; padding-top: 4px;">
<h1 style="margin: 0; font-family: Archivo, 'Archivo Narrow', 'Arial Narrow', 'Helvetica Neue Condensed', 'Liberation Sans Narrow', Arial, sans-serif; font-stretch: 82%; font-weight: 800; font-size: 26px; line-height: 1.0; letter-spacing: -0.6px; color: #172B4D; min-height: 56px;"><span style="white-space: nowrap;">Auto Dimensioning</span><br/><span style="color: #F28C28; white-space: nowrap;">&amp; Tagging</span></h1>
<h2 style="margin: 0; font-family: Archivo, 'Archivo Narrow', 'Arial Narrow', 'Helvetica Neue Condensed', 'Liberation Sans Narrow', Arial, sans-serif; font-stretch: 88%; font-weight: 600; font-size: 22px; line-height: 1.2; color: #5A626E;">Services dimensioned and tagged the same way on every drawing.</h2>

<div style="height: 48px; flex-shrink: 0; display: flex; align-items: center; justify-content: flex-start; gap: 22px; margin-top: auto;"><div style="display: flex; align-items: center; gap: 14px;"><div style="font-size: 15px; font-weight: 600; letter-spacing: -0.1px; color: #16181C; white-space: nowrap;">Add-in for</div><div style="width: 1px; height: 30px; background: #D5D9DF;"></div><img src="/logos/autocad.png" alt="Autodesk AutoCAD" width="34" height="34" style="display: block; width: 34px; height: 34px; object-fit: contain;"></div><a href="#demo" style="display: inline-flex; align-items: center; height: 44px; padding: 0 22px; border-radius: 6px; background: #F28C28; color: #FFFFFF; font-weight: 600; font-size: 15px; text-decoration: none;">Book a demo</a></div></div>
`;

/** Everything the markup binds to, for one position in the loop. */
export function values(p) {
  // p is the argument.
  function lin(k) {
    if (p <= k[0][0]) return k[0][1];
    for (var i = 1; i < k.length; i++) if (p <= k[i][0]) { var a = k[i-1], b = k[i], f = (p - a[0]) / (b[0] - a[0]); f = 1 - Math.pow(1 - f, 3); return a[1] + (b[1] - a[1]) * f; }
    return k[k.length-1][1];
  }
  var out = p < 94 ? 1 : Math.max(0, 1 - (p - 94) / 6);
  var v = {};
  function phases(ph) { for (var i = 0; i < ph.length; i++) { v['on'+i] = (p >= ph[i][0] && p < ph[i][1]) ? 1 : 0; v['done'+i] = (p >= ph[i][1] && p < 97) ? out : 0; } }

  phases([[0,14],[14,36],[36,62],[62,80]]);
  var nd = 0; for (var i = 0; i < 2; i++) { v['d'+i] = lin([[15 + i * 7, 0],[18 + i * 7, 1]]) * out; if (p >= 17 + i * 7) nd += 2; }
  var nt = 0; for (var i = 0; i < 3; i++) { v['t'+i] = lin([[38 + i * 5, 0],[41 + i * 5, 1]]) * out; if (p >= 40 + i * 5) nt++; }
  v.t3 = lin([[55,0],[59,1]]) * out;
  v.nd = nd; v.nt = nt; v.ne = p >= 58 ? 2 : 0;
  v.k0 = out; v.k1 = out; v.k2 = out; v.k3 = out;
  v.dw = (p >= 74 ? 4 : (p >= 70 ? 3 : (p >= 66 ? 2 : 1))) + ' / 4';
  v.fin = (p >= 76 && p < 97) ? out : 0;

  return { v: v };}

const card = { id, title, width, height, loopMs, attrs, stage, markup, values };
export default card;
