/* eslint-disable */
// @ts-nocheck
/**
 * Ramp &amp; Staircase Automation
 *
 * Generated by scripts/build-cards.mjs — do not edit. Both halves come out of
 * the design verbatim: `markup` is its stage, and `values` is its own
 * renderVals, untouched apart from taking the clock as an argument instead of
 * reading it off a component. See the script for the few things it adjusts.
 */

export const id = "revit-arch-ramp-staircase";
export const title = "Ramp &amp; Staircase Automation";
export const width = 476;
export const height = 356;
export const loopMs = 15000;

/**
 * The attributes this card drives, as the design lists them.
 *
 * Each bound node carries data-bind-<attr> holding a template like "[[wx]]",
 * which the scene fills from the frame's values.
 */
export const attrs = ["d"];

/** The stage's own styles, off the design's root element. */
export const stage = {
  "width": "476px",
  "height": "356px",
  "boxSizing": "border-box",
  "padding": "30px 48px 36px 48px",
  "display": "flex",
  "backgroundColor": "#FFFFFF",
  "color": "#16181C",
  "overflow": "hidden",
};

export const markup = `
<div style="width: 380px; flex-shrink: 0; height: 290px; display: flex; flex-direction: column; justify-content: flex-start; gap: 18px; padding-top: 4px;">
<h1 style="margin: 0; font-family: Archivo, 'Archivo Narrow', 'Arial Narrow', 'Helvetica Neue Condensed', 'Liberation Sans Narrow', Arial, sans-serif; font-stretch: 82%; font-weight: 800; font-size: 26px; line-height: 1.0; letter-spacing: -0.6px; color: #172B4D; min-height: 56px;"><span style="white-space: nowrap;">Ramp &amp; Staircase</span><br/><span style="color: #F28C28;">Automation</span></h1>
<h2 style="margin: 0; font-family: Archivo, 'Archivo Narrow', 'Arial Narrow', 'Helvetica Neue Condensed', 'Liberation Sans Narrow', Arial, sans-serif; font-stretch: 88%; font-weight: 600; font-size: 22px; line-height: 1.2; color: #5A626E;">Stairs and ramps from the floor height and your code preset.</h2>

<div style="height: 48px; flex-shrink: 0; display: flex; align-items: center; justify-content: flex-start; gap: 22px; margin-top: auto;"><div style="display: flex; align-items: center; gap: 14px;"><div style="font-size: 15px; font-weight: 600; letter-spacing: -0.1px; color: #16181C; white-space: nowrap;">Add-in for</div><div style="width: 1px; height: 30px; background: #D5D9DF;"></div><img src="/logos/revit.png" alt="Autodesk Revit" width="34" height="34" style="display: block; width: 34px; height: 34px; object-fit: contain;"></div><a href="#demo" style="display: inline-flex; align-items: center; height: 44px; padding: 0 22px; border-radius: 6px; background: #F28C28; color: #FFFFFF; font-weight: 600; font-size: 15px; text-decoration: none;">Book a demo</a></div></div>
`;

/** Everything the markup binds to, for one position in the loop. */
export function values(p) {
  // p is the argument.
  function lin(k) {
    if (p <= k[0][0]) return k[0][1];
    for (var i = 1; i < k.length; i++) if (p <= k[i][0]) { var a = k[i-1], b = k[i], f = (p - a[0]) / (b[0] - a[0]); f = 1 - Math.pow(1 - f, 3); return a[1] + (b[1] - a[1]) * f; }
    return k[k.length-1][1];
  }
  var out = p < 94 ? 1 : Math.max(0, 1 - (p - 94) / 6);
  var v = {};
  function phases(ph) { for (var i = 0; i < ph.length; i++) { v['on'+i] = (p >= ph[i][0] && p < ph[i][1]) ? 1 : 0; v['done'+i] = (p >= ph[i][1] && p < 97) ? out : 0; } }

  var D = {"S": 6.869103177970382, "OX": 25.7, "OY": 19.6, "r": [11, 36, 3, 9], "FH": 3.6, "NST": 20};
  phases([[0,12],[12,24],[24,46],[46,66],[66,80]]);
  v.pO = lin([[0,0],[3,1]]) * out; v.pT = 'translateY(' + lin([[0,14],[3,0]]).toFixed(1) + 'px)';
  v.arrO = lin([[13,0],[18,1]]) * out; v.landO = v.arrO;
  v.k0v = lin([[14,0],[17,1]]) * out; v.k1v = v.k0v; v.k2v = lin([[46,0],[49,1]]) * out;
  for (var i = 0; i < D.NST; i++) v['st'+i] = (p >= 24 + i * 1.0 ? 1 : 0) * out;
  v.lsO = lin([[24,0],[28,1]]) * out;
  var f = lin([[48,0],[62,1]]);
  var S=D.S, OX=D.OX, OY=D.OY, C=0.7071, H=0.7071*0.866, ZF=0.5;
  function P(x,y,z){ return ((x-y)*C*S+OX).toFixed(1)+','+((x+y)*H*S-z*ZF*S+OY).toFixed(1); }
  function q(a){ return 'M'+a.map(function(t){ return P(t[0],t[1],t[2]); }).join('L')+'Z'; }
  var x0=D.r[0], x1=D.r[0]+(D.r[1]-D.r[0])*Math.max(f,0.001), y0=D.r[2], y1=D.r[3], ze=D.FH*Math.max(f,0.001);
  v.rT = q([[x0,y0,0],[x1,y0,ze],[x1,y1,ze],[x0,y1,0]]);
  v.rS = q([[x0,y1,0],[x1,y1,0],[x1,y1,ze]]);
  v.rE = q([[x1,y0,0],[x1,y1,0],[x1,y1,ze],[x1,y0,ze]]);
  v.rO = (f > 0.005 ? 1 : 0) * out; v.lrO = lin([[48,0],[52,1]]) * out; v.chO = lin([[60,0],[64,1]]) * out;
  v.k0 = (p >= 68 && p < 97) ? out : 0; v.k1 = (p >= 70 && p < 97) ? out : 0; v.k2 = (p >= 72 && p < 97) ? out : 0;
  v.fin = (p >= 75 && p < 97) ? out : 0;

  return { v: v };}

const card = { id, title, width, height, loopMs, attrs, stage, markup, values };
export default card;
