/* eslint-disable */
// @ts-nocheck
/**
 * CAD2RVT – CAD to Revit Automation
 *
 * Generated by scripts/build-cards.mjs — do not edit. Both halves come out of
 * the design verbatim: `markup` is its stage, and `values` is its own
 * renderVals, untouched apart from taking the clock as an argument instead of
 * reading it off a component. See the script for the few things it adjusts.
 */

export const id = "revit-arch-cad2rvt";
export const title = "CAD2RVT – CAD to Revit Automation";
export const width = 476;
export const height = 356;
export const loopMs = 14000;

/**
 * The attributes this card drives, as the design lists them.
 *
 * Each bound node carries data-bind-<attr> holding a template like "[[wx]]",
 * which the scene fills from the frame's values.
 */
export const attrs = ["d"];

/** The stage's own styles, off the design's root element. */
export const stage = {
  "width": "476px",
  "height": "356px",
  "boxSizing": "border-box",
  "padding": "30px 48px 36px 48px",
  "display": "flex",
  "backgroundColor": "#FFFFFF",
  "color": "#16181C",
  "overflow": "hidden",
};

export const markup = `
<div style="width: 380px; flex-shrink: 0; height: 290px; display: flex; flex-direction: column; justify-content: flex-start; gap: 18px; padding-top: 4px;">
<h1 style="margin: 0; font-family: Archivo, 'Archivo Narrow', 'Arial Narrow', 'Helvetica Neue Condensed', 'Liberation Sans Narrow', Arial, sans-serif; font-stretch: 82%; font-weight: 800; font-size: 26px; line-height: 1.0; letter-spacing: -0.6px; color: #172B4D; min-height: 56px;"><span style="white-space: nowrap;">CAD to Revit</span><br/><span style="color: #F28C28;">Automation</span></h1>
<h2 style="margin: 0; font-family: Archivo, 'Archivo Narrow', 'Arial Narrow', 'Helvetica Neue Condensed', 'Liberation Sans Narrow', Arial, sans-serif; font-stretch: 88%; font-weight: 600; font-size: 22px; line-height: 1.2; color: #5A626E;">Drop in the CAD plan. Build the Revit model step by step.</h2>

<div style="height: 48px; flex-shrink: 0; display: flex; align-items: center; justify-content: flex-start; gap: 22px; margin-top: auto;"><div style="display: flex; align-items: center; gap: 14px;"><div style="font-size: 15px; font-weight: 600; letter-spacing: -0.1px; color: #16181C; white-space: nowrap;">Add-in for</div><div style="width: 1px; height: 30px; background: #D5D9DF;"></div><img src="/logos/revit.png" alt="Autodesk Revit" width="34" height="34" style="display: block; width: 34px; height: 34px; object-fit: contain;"></div><a href="#demo" style="display: inline-flex; align-items: center; height: 44px; padding: 0 22px; border-radius: 6px; background: #F28C28; color: #FFFFFF; font-weight: 600; font-size: 15px; text-decoration: none;">Book a demo</a></div></div>
`;

/** Everything the markup binds to, for one position in the loop. */
export function values(p) {
  // p is the argument.
  function lin(k) {
    if (p <= k[0][0]) return k[0][1];
    for (var i = 1; i < k.length; i++) {
      if (p <= k[i][0]) { var a = k[i-1], b = k[i], f = (p - a[0]) / (b[0] - a[0]); f = 1 - Math.pow(1 - f, 3); return a[1] + (b[1] - a[1]) * f; }
    }
    return k[k.length-1][1];
  }
  var out = p < 94 ? 1 : Math.max(0, 1 - (p - 94) / 6);
  var ph = [[0,12],[12,28],[28,46],[46,62],[62,80]];
  var v = {};
  for (var i = 0; i < 5; i++) {
    v['on' + i] = (p >= ph[i][0] && p < ph[i][1]) ? 1 : 0;
    v['done' + i] = (p >= ph[i][1] && p < 97) ? out : 0;
  }
  var dO = lin([[0,0],[4,1],[9,1],[12,0]]), dY = lin([[0,-60],[4,0],[9,0],[12,40]]), dS = lin([[0,.9],[4,1],[9,1],[12,.6]]);
  v.dwgO = dO; v.dwgT = 'translateY(' + dY.toFixed(1) + 'px) scale(' + dS.toFixed(3) + ')';
  v.cad = lin([[8,0],[12,1],[40,1],[50,.2]]) * out;
  var sO = lin([[12,0],[20,1]]);
  v.slabO = sO * out; v.slabT = 'translateY(' + (14 * (1 - sO)).toFixed(1) + 'px)';
  var w = lin([[28,0],[42,1]]), d = lin([[46,0],[56,1]]), fm = lin([[62,0],[72,1]]);
  
  var S=34, OX=261, OY=75, C=0.7071, H=0.7071*0.866, ZF=0.5;
  function P(x,y,z){ return ((x-y)*C*S+OX).toFixed(1)+','+((x+y)*H*S-z*ZF*S+OY).toFixed(1); }
  function poly(a){ return 'M'+a.map(function(q){return P(q[0],q[1],q[2]);}).join('L')+'Z'; }
  var RUNS=[["x", 0, 0, 10, 0.2, null], ["y", 0, 0.2, 0.2, 7, null], ["x", 0.2, 6.8, 10, 7, [2, 3.2]], ["y", 9.8, 0.2, 10, 6.8, null], ["y", 5.9, 0.2, 6.1, 6.8, [3, 4]], ["x", 6.1, 4.4, 9.8, 4.6, [7, 7.9]]], DOORS=[[2, 6.86, 3.2, 6.94], [5.96, 3, 6.04, 4], [7, 4.46, 7.9, 4.54]];
  var hW=Math.max(3*w,0.001), hD=Math.max(2.1*d,0.001), dh=Math.min(2.1,hW);
  RUNS.forEach(function(r,i){
    var ax=r[0],x0=r[1],y0=r[2],x1=r[3],y1=r[4],g=r[5],o={};
    o.top=poly([[x0,y0,hW],[x1,y0,hW],[x1,y1,hW],[x0,y1,hW]]);
    if(ax==='x'){
      o.front=poly([[x0,y1,0],[x1,y1,0],[x1,y1,hW],[x0,y1,hW]]);
      o.end=poly([[x1,y0,0],[x1,y1,0],[x1,y1,hW],[x1,y0,hW]]);
      if(g){ o.front+=poly([[g[0],y1,0],[g[1],y1,0],[g[1],y1,dh],[g[0],y1,dh]]); o.rev=poly([[g[0],y0,0],[g[0],y1,0],[g[0],y1,dh],[g[0],y0,dh]]); } else o.rev='';
    } else {
      o.front=poly([[x1,y0,0],[x1,y1,0],[x1,y1,hW],[x1,y0,hW]]);
      o.end=poly([[x0,y1,0],[x1,y1,0],[x1,y1,hW],[x0,y1,hW]]);
      if(g){ o.front+=poly([[x1,g[0],0],[x1,g[1],0],[x1,g[1],dh],[x1,g[0],dh]]); o.rev=poly([[x0,g[0],0],[x1,g[0],0],[x1,g[0],dh],[x0,g[0],dh]]); } else o.rev='';
    }
    v['w'+i]=o;
  });
  DOORS.forEach(function(b,k){
    var x0=b[0],y0=b[1],x1=b[2],y1=b[3];
    v['d'+k]={ top:poly([[x0,y0,hD],[x1,y0,hD],[x1,y1,hD],[x0,y1,hD]]),
      fy:poly([[x0,y1,0],[x1,y1,0],[x1,y1,hD],[x0,y1,hD]]),
      fx:poly([[x1,y0,0],[x1,y1,0],[x1,y1,hD],[x1,y0,hD]]) };
  });
  v.wo = w > 0.01 ? out : 0; v.do = d > 0.01 ? out : 0;

  v.fam = 'opacity: ' + (fm * out).toFixed(3) + '; transform: translateY(' + (-22 * (1 - fm)).toFixed(1) + 'px);';
  return { v: v };}

const card = { id, title, width, height, loopMs, attrs, stage, markup, values };
export default card;
