/* eslint-disable */
// @ts-nocheck
/**
 * Ceiling Generation Automation
 *
 * Generated by scripts/build-cards.mjs — do not edit. Both halves come out of
 * the design verbatim: `markup` is its stage, and `values` is its own
 * renderVals, untouched apart from taking the clock as an argument instead of
 * reading it off a component. See the script for the few things it adjusts.
 */

export const id = "revit-arch-ceiling-generation";
export const title = "Ceiling Generation Automation";
export const width = 476;
export const height = 356;
export const loopMs = 15000;

/**
 * The attributes this card drives, as the design lists them.
 *
 * Each bound node carries data-bind-<attr> holding a template like "[[wx]]",
 * which the scene fills from the frame's values.
 */
export const attrs = [];

/** The stage's own styles, off the design's root element. */
export const stage = {
  "width": "476px",
  "height": "356px",
  "boxSizing": "border-box",
  "padding": "30px 48px 36px 48px",
  "display": "flex",
  "backgroundColor": "#FFFFFF",
  "color": "#16181C",
  "overflow": "hidden",
};

export const markup = `
<div style="width: 380px; flex-shrink: 0; height: 290px; display: flex; flex-direction: column; justify-content: flex-start; gap: 18px; padding-top: 4px;">
<h1 style="margin: 0; font-family: Archivo, 'Archivo Narrow', 'Arial Narrow', 'Helvetica Neue Condensed', 'Liberation Sans Narrow', Arial, sans-serif; font-stretch: 82%; font-weight: 800; font-size: 26px; line-height: 1.0; letter-spacing: -0.6px; color: #172B4D; min-height: 56px;"><span style="white-space: nowrap;">Ceiling Generation</span><br/><span style="color: #F28C28;">Automation</span></h1>
<h2 style="margin: 0; font-family: Archivo, 'Archivo Narrow', 'Arial Narrow', 'Helvetica Neue Condensed', 'Liberation Sans Narrow', Arial, sans-serif; font-stretch: 88%; font-weight: 600; font-size: 22px; line-height: 1.2; color: #5A626E;">Ceilings in every room from the types and heights in your Excel.</h2>

<div style="height: 48px; flex-shrink: 0; display: flex; align-items: center; justify-content: flex-start; gap: 22px; margin-top: auto;"><div style="display: flex; align-items: center; gap: 14px;"><div style="font-size: 15px; font-weight: 600; letter-spacing: -0.1px; color: #16181C; white-space: nowrap;">Add-in for</div><div style="width: 1px; height: 30px; background: #D5D9DF;"></div><img src="/logos/revit.png" alt="Autodesk Revit" width="34" height="34" style="display: block; width: 34px; height: 34px; object-fit: contain;"></div><a href="#demo" style="display: inline-flex; align-items: center; height: 44px; padding: 0 22px; border-radius: 6px; background: #F28C28; color: #FFFFFF; font-weight: 600; font-size: 15px; text-decoration: none;">Book a demo</a></div></div>
`;

/** Everything the markup binds to, for one position in the loop. */
export function values(p) {
  // p is the argument.
  function lin(k) {
    if (p <= k[0][0]) return k[0][1];
    for (var i = 1; i < k.length; i++) if (p <= k[i][0]) { var a = k[i-1], b = k[i], f = (p - a[0]) / (b[0] - a[0]); f = 1 - Math.pow(1 - f, 3); return a[1] + (b[1] - a[1]) * f; }
    return k[k.length-1][1];
  }
  var out = p < 94 ? 1 : Math.max(0, 1 - (p - 94) / 6);
  var v = {};
  function phases(ph) { for (var i = 0; i < ph.length; i++) { v['on'+i] = (p >= ph[i][0] && p < ph[i][1]) ? 1 : 0; v['done'+i] = (p >= ph[i][1] && p < 97) ? out : 0; } }

  var D = {"N": 12, "NX": 6, "NT": 3};
  phases([[0,14],[14,28],[28,42],[42,78]]);
  v.xO = lin([[0,0],[3,1]]) * out; v.xT = 'translateX(' + lin([[0,24],[3,0]]).toFixed(1) + 'px)';
  for (var i = 0; i < D.NX; i++) v['x'+i] = (p >= 3 + i * 1.5 ? 1 : 0);
  v.rmO = lin([[14,0],[18,1]]) * out; v.wO = lin([[16,0],[22,1]]) * out;
  v.tyO = lin([[28,0],[31,1]]) * out;
  for (var i = 0; i < D.NT; i++) v['ty'+i] = (p >= 31 + i * 3 ? 1 : 0);
  for (var i = 0; i < D.N; i++) {
    var t = 42 + i * 2.6, f = lin([[t,0],[t+2,1]]);
    v['c'+i] = 'opacity: ' + ((f > 0.01 ? 1 : 0) * out) + '; transform: translateY(' + (-26 * (1 - f)).toFixed(1) + 'px);';
    v['tg'+i] = (p >= t + 2 && p < 97) ? out : 0;
  }
  v.fin = (p >= 76 && p < 97) ? out : 0;

  return { v: v };}

const card = { id, title, width, height, loopMs, attrs, stage, markup, values };
export default card;
