/* eslint-disable */
// @ts-nocheck
/**
 * Equipment Placement Automation
 *
 * Generated by scripts/build-cards.mjs — do not edit. Both halves come out of
 * the design verbatim: `markup` is its stage, and `values` is its own
 * renderVals, untouched apart from taking the clock as an argument instead of
 * reading it off a component. See the script for the few things it adjusts.
 */

export const id = "revit-mep-equipment-placement";
export const title = "Equipment Placement Automation";
export const width = 476;
export const height = 356;
export const loopMs = 15000;

/**
 * The attributes this card drives, as the design lists them.
 *
 * Each bound node carries data-bind-<attr> holding a template like "[[wx]]",
 * which the scene fills from the frame's values.
 */
export const attrs = ["fill","stroke"];

/** The stage's own styles, off the design's root element. */
export const stage = {
  "width": "476px",
  "height": "356px",
  "boxSizing": "border-box",
  "padding": "30px 48px 36px 48px",
  "display": "flex",
  "backgroundColor": "#FFFFFF",
  "color": "#16181C",
  "overflow": "hidden",
};

export const markup = `
<div style="width: 380px; flex-shrink: 0; height: 290px; display: flex; flex-direction: column; justify-content: flex-start; gap: 18px; padding-top: 4px;">
<h1 style="margin: 0; font-family: Archivo, 'Archivo Narrow', 'Arial Narrow', 'Helvetica Neue Condensed', 'Liberation Sans Narrow', Arial, sans-serif; font-stretch: 82%; font-weight: 800; font-size: 26px; line-height: 1.0; letter-spacing: -0.6px; color: #172B4D; min-height: 56px;"><span style="white-space: nowrap;">Equipment Placement</span><br/><span style="color: #F28C28; white-space: nowrap;">Automation</span></h1>
<h2 style="margin: 0; font-family: Archivo, 'Archivo Narrow', 'Arial Narrow', 'Helvetica Neue Condensed', 'Liberation Sans Narrow', Arial, sans-serif; font-stretch: 88%; font-weight: 600; font-size: 22px; line-height: 1.2; color: #5A626E;">Equipment placed at set locations, clearances checked and fixed.</h2>

<div style="height: 48px; flex-shrink: 0; display: flex; align-items: center; justify-content: flex-start; gap: 22px; margin-top: auto;"><div style="display: flex; align-items: center; gap: 14px;"><div style="font-size: 15px; font-weight: 600; letter-spacing: -0.1px; color: #16181C; white-space: nowrap;">Add-in for</div><div style="width: 1px; height: 30px; background: #D5D9DF;"></div><img src="/logos/revit.png" alt="Autodesk Revit" width="34" height="34" style="display: block; width: 34px; height: 34px; object-fit: contain;"></div><a href="#demo" style="display: inline-flex; align-items: center; height: 44px; padding: 0 22px; border-radius: 6px; background: #F28C28; color: #FFFFFF; font-weight: 600; font-size: 15px; text-decoration: none;">Book a demo</a></div></div>
`;

/** Everything the markup binds to, for one position in the loop. */
export function values(p) {
  // p is the argument.
  function lin(k) {
    if (p <= k[0][0]) return k[0][1];
    for (var i = 1; i < k.length; i++) if (p <= k[i][0]) { var a = k[i-1], b = k[i], f = (p - a[0]) / (b[0] - a[0]); f = 1 - Math.pow(1 - f, 3); return a[1] + (b[1] - a[1]) * f; }
    return k[k.length-1][1];
  }
  var out = p < 94 ? 1 : Math.max(0, 1 - (p - 94) / 6);
  var v = {};
  function phases(ph) { for (var i = 0; i < ph.length; i++) { v['on'+i] = (p >= ph[i][0] && p < ph[i][1]) ? 1 : 0; v['done'+i] = (p >= ph[i][1] && p < 97) ? out : 0; } }

  phases([[0,14],[14,40],[40,62],[62,80]]);
  v.sp = lin([[2,0],[8,1],[40,1],[46,0]]) * out;
  for (var i = 0; i < 5; i++) { var f = lin([[15 + i * 4, 0],[18 + i * 4, 1]]); var dx = (i == 2) ? 8 * lin([[62,0],[66,1]]) : 0; v['e'+i] = 'opacity: ' + (f * out).toFixed(3) + '; transform: translate(' + (-dx).toFixed(1) + 'px,' + (-10 * (1 - f)).toFixed(1) + 'px);'; }
  v.cl = lin([[42,0],[48,1]]) * out;
  var bad = (p >= 48 && p < 64);
  for (var i = 0; i < 5; i++) { var red = bad && (i == 1 || i == 2); v['cf'+i] = red ? 'rgba(192,57,43,0.12)' : 'rgba(30,127,79,0.08)'; v['cs'+i] = red ? '#C0392B' : '#1E7F4F'; }
  v.cc = bad ? 'CHP-1/2 overlap' : (p >= 64 ? 'all met' : '—');
  v.k0 = p >= 36 ? out : 0.25 * out; v.k1 = p >= 48 ? out : 0.25 * out; v.k2 = p >= 56 ? out : 0.25 * out; v.k3 = p >= 68 ? out : 0.25 * out;
  v.fin = (p >= 72 && p < 97) ? out : 0;

  return { v: v };}

const card = { id, title, width, height, loopMs, attrs, stage, markup, values };
export default card;
