import type { ToolSeed } from "./shared";

/**
 * Architecture — 37 products: 25 Revit add-ins and 12 for AutoCAD.
 *
 * Generated by scripts/build-catalogue.mjs from the cards in cards/ — do not
 * edit. Every name, sentence and step comes off the card that shows it, so the
 * page and the animation can never drift apart. The one hand-written input is
 * scripts/summaries.json, which holds the supplied product descriptions.
 *
 * A tool that exists for both applications is two products here, because it is
 * two products: different work, different card, different add-in.
 */
export const architectureTools: ToolSeed[] = [
  /* 1 --------------------------------------------------------------- */
  {
    id: "revit-arch-cad2rvt",
    name: "CAD2RVT – CAD to Revit Automation",
    slug: "revit-arch-cad2rvt",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Drop in the CAD plan. Build the Revit model step by step.",
    description:
      "Drop in the CAD plan. Build the Revit model step by step.",
    what: [
      "What it runs through, in order: link the dwg, slabs, walls, doors.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Link the DWG",
      "Slabs",
      "Walls",
      "Doors",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 2 --------------------------------------------------------------- */
  {
    id: "revit-arch-site-feasibility",
    name: "Site & Feasibility Automation",
    slug: "revit-arch-site-feasibility",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Drop in the site plan. Get massing options in Revit.",
    description:
      "Drop in the site plan. Get massing options in Revit.",
    what: [
      "What it runs through, in order: link the site dwg, boundary, setbacks, levels.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Link the site DWG",
      "Boundary",
      "Setbacks",
      "Levels",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 3 --------------------------------------------------------------- */
  {
    id: "revit-arch-concept-design",
    name: "Concept Design Automation",
    slug: "revit-arch-concept-design",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Generate and compare different unit mix options based on the required unit types and target areas.",
    description:
      "Set the unit mix. Get layout options to compare.",
    what: [
      "What it runs through, in order: unit requirements, read the floor plate, generate layouts, compare options.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Unit requirements",
      "Read the floor plate",
      "Generate layouts",
      "Compare options",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 4 --------------------------------------------------------------- */
  {
    id: "revit-arch-unit-planning",
    name: "Unit Planning Automation",
    slug: "revit-arch-unit-planning",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Generate optimized unit designs using AI-powered automation.",
    description:
      "Rooms, walls, doors and tags generated inside every unit.",
    what: [
      "What it runs through, in order: pick the units, set layout rules, zone the rooms, walls & doors.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick the units",
      "Set layout rules",
      "Zone the rooms",
      "Walls & doors",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 5 --------------------------------------------------------------- */
  {
    id: "revit-arch-area-calculation",
    name: "Area Calculation Automation",
    slug: "revit-arch-area-calculation",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically calculate GFA, BUA, FAR/FSI, site area, garbage, parking, and other project areas.",
    description:
      "Every project area calculated, and checked against your rules.",
    what: [
      "What it runs through, in order: set your rules, area boundaries, classify areas, calculate & check.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Set your rules",
      "Area boundaries",
      "Classify areas",
      "Calculate & check",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 6 --------------------------------------------------------------- */
  {
    id: "revit-arch-area-plan-generation",
    name: "Area Plan Generation",
    slug: "revit-arch-area-plan-generation",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically generate area plans and calculate the areas of spaces and zones.",
    description:
      "Area plans for every level, with zones and areas calculated.",
    what: [
      "What it runs through, in order: area scheme, create area plans, zone boundaries, areas & totals.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Area scheme",
      "Create area plans",
      "Zone boundaries",
      "Areas & totals",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 7 --------------------------------------------------------------- */
  {
    id: "revit-arch-schedule",
    name: "Schedule Automation",
    slug: "revit-arch-schedule",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically create and update Revit schedules from model information.",
    description:
      "Export to Excel, edit there, push the changes back to Revit.",
    what: [
      "What it runs through, in order: pick schedules, export to excel, edit in excel, push back to revit.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick schedules",
      "Export to Excel",
      "Edit in Excel",
      "Push back to Revit",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 8 --------------------------------------------------------------- */
  {
    id: "revit-arch-parking-mobility",
    name: "Parking & Mobility Automation",
    slug: "revit-arch-parking-mobility",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically generate parking layouts with code-compliant space dimensions and circulation.",
    description:
      "Parking laid out to code, with accessible and EV bays and flow.",
    what: [
      "What it runs through, in order: parking code, read the level, place the bays, accessible & ev.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Parking code",
      "Read the level",
      "Place the bays",
      "Accessible & EV",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 9 --------------------------------------------------------------- */
  {
    id: "revit-arch-ramp-staircase",
    name: "Ramp & Staircase Automation",
    slug: "revit-arch-ramp-staircase",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically generate ramps and staircases based on project parameters.",
    description:
      "Stairs and ramps from the floor height and your code preset.",
    what: [
      "What it runs through, in order: project parameters, stair layout, create the stair, create the ramp.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Project parameters",
      "Stair layout",
      "Create the stair",
      "Create the ramp",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 10 -------------------------------------------------------------- */
  {
    id: "revit-arch-ceiling-generation",
    name: "Ceiling Generation Automation",
    slug: "revit-arch-ceiling-generation",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically generate ceiling layouts and place required ceiling elements.",
    description:
      "Ceilings in every room from the types and heights in your Excel.",
    what: [
      "What it runs through, in order: ceiling data in excel, read the rooms, create ceiling types, generate ceilings.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Ceiling data in Excel",
      "Read the rooms",
      "Create ceiling types",
      "Generate ceilings",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 11 -------------------------------------------------------------- */
  {
    id: "revit-arch-detailed-design",
    name: "Detailed Design Automation",
    slug: "revit-arch-detailed-design",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automate repetitive detailing for doors, windows, curtain walls, kitchens, toilets, joinery, and finishes.",
    description:
      "Annotated detail views for toilets, kitchens, doors and windows.",
    what: [
      "What it runs through, in order: pick by room type, place callouts, generate views, annotate by rules.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick by room type",
      "Place callouts",
      "Generate views",
      "Annotate by rules",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 12 -------------------------------------------------------------- */
  {
    id: "revit-arch-parameter",
    name: "Parameter Automation",
    slug: "revit-arch-parameter",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically create, rename, update, and manage Revit parameters and project data, even inside linked models.",
    description:
      "Create, rename and fill parameters, even inside linked models.",
    what: [
      "What it runs through, in order: define parameters, create & rename, fill values, update linked models.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Define parameters",
      "Create & rename",
      "Fill values",
      "Update linked models",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 13 -------------------------------------------------------------- */
  {
    id: "revit-arch-clash-detection",
    name: "Coordination & Clash Detection Automation",
    slug: "revit-arch-clash-detection",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically create a 3D clash view inside Revit, with each clash marked by a flag that can be clicked to view its details.",
    description:
      "A 3D clash view in Revit, with a clickable flag at every clash.",
    what: [
      "What it runs through, in order: pick disciplines, run the check, 3d clash view, click a flag.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick disciplines",
      "Run the check",
      "3D clash view",
      "Click a flag",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 14 -------------------------------------------------------------- */
  {
    id: "revit-arch-interior-shop-drawing",
    name: "Interior Shop Drawing Automation",
    slug: "revit-arch-interior-shop-drawing",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically create the complete interior shop drawing, including layouts, interior elements, finishes, cut openings, and associated documentation.",
    description:
      "Layouts, finishes, ceiling openings and elevations, annotated.",
    what: [
      "What it runs through, in order: layout & elements, finishes, ceiling openings, elevations.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Layout & elements",
      "Finishes",
      "Ceiling openings",
      "Elevations",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 15 -------------------------------------------------------------- */
  {
    id: "revit-arch-toilet-shop-drawing",
    name: "Toilet Shop Drawing Automation",
    slug: "revit-arch-toilet-shop-drawing",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically create the complete toilet shop drawing, including the layout, sanitary fixtures, partitions, finishes, cut openings, and associated documentation.",
    description:
      "Cubicles, tiles, heights and cut-outs, as annotated views.",
    what: [
      "What it runs through, in order: layout & partitions, tile setting-out, mounting heights, counter cut-outs.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Layout & partitions",
      "Tile setting-out",
      "Mounting heights",
      "Counter cut-outs",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 16 -------------------------------------------------------------- */
  {
    id: "revit-arch-kitchen-shop-drawing",
    name: "Kitchen Shop Drawing Automation",
    slug: "revit-arch-kitchen-shop-drawing",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically create the complete kitchen shop drawing, including the layout, cabinetry, fixtures, finishes, and associated documentation.",
    description:
      "Cabinets, worktop cut-outs, appliances and a cabinet schedule.",
    what: [
      "What it runs through, in order: cabinet modules, worktop set-out, appliance openings, cabinet schedule.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Cabinet modules",
      "Worktop set-out",
      "Appliance openings",
      "Cabinet schedule",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 17 -------------------------------------------------------------- */
  {
    id: "revit-arch-ceiling-shop-drawing",
    name: "Ceiling Shop Drawing Automation",
    slug: "revit-arch-ceiling-shop-drawing",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically create the complete ceiling shop drawing, including the framing model, cut openings, and associated documentation.",
    description:
      "Ceiling framing from your Excel and spacing, then detailed.",
    what: [
      "What it runs through, in order: thickness from excel, framing model, access panel cut-outs, detailing.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Thickness from Excel",
      "Framing model",
      "Access panel cut-outs",
      "Detailing",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 18 -------------------------------------------------------------- */
  {
    id: "revit-arch-drywall-shop-drawing",
    name: "Drywall Shop Drawing Automation",
    slug: "revit-arch-drywall-shop-drawing",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically create the complete drywall shop drawing, including the partition layout, framing model, cut openings, and associated documentation.",
    description:
      "Partitions framed at your stud spacing, openings cut, detailed.",
    what: [
      "What it runs through, in order: partition layout, framing model, door & window openings, detailing.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Partition layout",
      "Framing model",
      "Door & window openings",
      "Detailing",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 19 -------------------------------------------------------------- */
  {
    id: "revit-arch-wardrobe-shop-drawing",
    name: "Wardrobe Shop Drawing Automation",
    slug: "revit-arch-wardrobe-shop-drawing",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically create the complete wardrobe shop drawing, including the layout, carcass, doors, hardware, and associated documentation.",
    description:
      "Carcasses, internals, doors and hardware, as annotated views.",
    what: [
      "What it runs through, in order: carcass layout, internal fittings, doors & hinges, hardware schedule.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Carcass layout",
      "Internal fittings",
      "Doors & hinges",
      "Hardware schedule",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 20 -------------------------------------------------------------- */
  {
    id: "revit-arch-as-built",
    name: "As-Built Drawing Automation",
    slug: "revit-arch-as-built",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically generate accurate as-built drawings from the final BIM model.",
    description:
      "Drawings updated from the final model and stamped AS-BUILT.",
    what: [
      "What it runs through, in order: final model in, update views & tags, stamp as-built, set ready.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Final model in",
      "Update views & tags",
      "Stamp AS-BUILT",
      "Set ready",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 21 -------------------------------------------------------------- */
  {
    id: "revit-arch-view-sheet-generation",
    name: "Automatic View & Sheet Generation",
    slug: "revit-arch-view-sheet-generation",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically generate views and sheets, and place the views on the sheets in an organized layout.",
    description:
      "Views per level, placed on sheets in an organised layout.",
    what: [
      "What it runs through, in order: pick levels & templates, create views, create sheets, place views.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick levels & templates",
      "Create views",
      "Create sheets",
      "Place views",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 22 -------------------------------------------------------------- */
  {
    id: "revit-arch-pdf-dwg-exporter",
    name: "PDF & DWG Exporter",
    slug: "revit-arch-pdf-dwg-exporter",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Export up to 300 sheets to PDF and DWG in just five minutes, directly from Revit.",
    description:
      "Hundreds of sheets to PDF and DWG in minutes, from Revit.",
    what: [
      "What it runs through, in order: select sheets, formats & naming, batch export, organised output.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Select sheets",
      "Formats & naming",
      "Batch export",
      "Organised output",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 23 -------------------------------------------------------------- */
  {
    id: "revit-arch-nwf-nwd-nwc-ifc-exporter",
    name: "NWF, NWD, NWC & IFC Exporter",
    slug: "revit-arch-nwf-nwd-nwc-ifc-exporter",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically export NWF, NWD, NWC, IFC, and other coordination files for seamless project coordination.",
    description:
      "Models exported to NWC and IFC, then combined into NWF and NWD.",
    what: [
      "What it runs through, in order: pick models, export nwc & ifc, build nwf, publish nwd.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick models",
      "Export NWC & IFC",
      "Build NWF",
      "Publish NWD",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 24 -------------------------------------------------------------- */
  {
    id: "revit-arch-scan-to-bim",
    name: "Scan-to-BIM Automation",
    slug: "revit-arch-scan-to-bim",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically convert point-cloud scans into accurate, structured Revit models.",
    description:
      "Point-cloud scans turned into Revit walls, doors and ceilings.",
    what: [
      "What it runs through, in order: load the scan, walls & floors, doors & windows, ceilings.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Load the scan",
      "Walls & floors",
      "Doors & windows",
      "Ceilings",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 25 -------------------------------------------------------------- */
  {
    id: "revit-arch-auto-dimensioning-tagging",
    name: "Auto Dimensioning & Tagging",
    slug: "revit-arch-auto-dimensioning-tagging",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically add dimensions between walls, interior elements, and lighting fixtures while intelligently positioning tags.",
    description:
      "Wall-to-wall and element dimensions, tags aligned on the side you choose.",
    what: [
      "What it runs through, in order: wall to wall, element to element, tags with arrows, align to any side.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Wall to wall",
      "Element to element",
      "Tags with arrows",
      "Align to any side",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 26 -------------------------------------------------------------- */
  {
    id: "acad-arch-pdf-dwg-exporter",
    name: "PDF & DWG Exporter",
    slug: "acad-arch-pdf-dwg-exporter",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Hundreds of CAD layouts batch-exported to standard PDF and DWG.",
    description:
      "Hundreds of CAD layouts batch-exported to standard PDF and DWG.",
    what: [
      "What it runs through, in order: pick drawings, page setup, batch export, named & filed.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick drawings",
      "Page setup",
      "Batch export",
      "Named & filed",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 27 -------------------------------------------------------------- */
  {
    id: "acad-arch-layer-standardization",
    name: "Layer Standardization",
    slug: "acad-arch-layer-standardization",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "New drawings matched to your template's layers and properties.",
    description:
      "New drawings matched to your template's layers and properties.",
    what: [
      "What it runs through, in order: load template, map layers, apply properties, whole set.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Load template",
      "Map layers",
      "Apply properties",
      "Whole set",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 28 -------------------------------------------------------------- */
  {
    id: "acad-arch-batch-drawing-cleanup",
    name: "Batch Drawing Cleanup",
    slug: "acad-arch-batch-drawing-cleanup",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Duplicates, unused layers, strays and errors removed in batch.",
    description:
      "Duplicates, unused layers, strays and errors removed in batch.",
    what: [
      "What it runs through, in order: scan drawings, overkill, purge & audit, whole set.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Scan drawings",
      "Overkill",
      "Purge & audit",
      "Whole set",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 29 -------------------------------------------------------------- */
  {
    id: "acad-arch-auto-dimensioning-tagging",
    name: "Auto Dimensioning & Tagging",
    slug: "acad-arch-auto-dimensioning-tagging",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Dimensions and tags placed the same way on every drawing.",
    description:
      "Dimensions and tags placed the same way on every drawing.",
    what: [
      "What it runs through, in order: pick rules, dimensions, tags, whole set.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick rules",
      "Dimensions",
      "Tags",
      "Whole set",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 30 -------------------------------------------------------------- */
  {
    id: "acad-arch-drawing-annotation",
    name: "Drawing Annotation Automation",
    slug: "acad-arch-drawing-annotation",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Notes, labels, callouts and symbols placed by your rules.",
    description:
      "Notes, labels, callouts and symbols placed by your rules.",
    what: [
      "What it runs through, in order: room labels, notes, callouts, symbols.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Room labels",
      "Notes",
      "Callouts",
      "Symbols",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 31 -------------------------------------------------------------- */
  {
    id: "acad-arch-elevation-section-update",
    name: "Elevation & Section Update Automation",
    slug: "acad-arch-elevation-section-update",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Elevations and sections updated when the plan changes.",
    description:
      "Elevations and sections updated when the plan changes.",
    what: [
      "What it runs through, in order: detect plan change, update elevations, update sections, linked sheets.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Detect plan change",
      "Update elevations",
      "Update sections",
      "Linked sheets",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 32 -------------------------------------------------------------- */
  {
    id: "acad-arch-area-quantity-extraction",
    name: "Area & Quantity Extraction",
    slug: "acad-arch-area-quantity-extraction",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Room and floor areas taken off many drawings, no measuring.",
    description:
      "Room and floor areas taken off many drawings, no measuring.",
    what: [
      "What it runs through, in order: pick drawings, detect rooms, measure, export.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick drawings",
      "Detect rooms",
      "Measure",
      "Export",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 33 -------------------------------------------------------------- */
  {
    id: "acad-arch-schedule-extraction",
    name: "Schedule Extraction Automation",
    slug: "acad-arch-schedule-extraction",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Door, window, room and finish schedules built from the drawings.",
    description:
      "Door, window, room and finish schedules built from the drawings.",
    what: [
      "What it runs through, in order: read blocks, door & window, rooms & finishes, update sheet.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Read blocks",
      "Door & window",
      "Rooms & finishes",
      "Update sheet",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 34 -------------------------------------------------------------- */
  {
    id: "acad-arch-sheet-layout",
    name: "Sheet & Layout Automation",
    slug: "acad-arch-sheet-layout",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Layouts, title blocks, numbers, revisions and viewports.",
    description:
      "Layouts, title blocks, numbers, revisions and viewports.",
    what: [
      "What it runs through, in order: create layouts, title blocks, viewports, revisions.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Create layouts",
      "Title blocks",
      "Viewports",
      "Revisions",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 35 -------------------------------------------------------------- */
  {
    id: "acad-arch-viewport-scale",
    name: "Viewport & Scale Automation",
    slug: "acad-arch-viewport-scale",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Viewport scales, orientation and positions made consistent.",
    description:
      "Viewport scales, orientation and positions made consistent.",
    what: [
      "What it runs through, in order: scan sheets, set scale, align, visibility & lock.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Scan sheets",
      "Set scale",
      "Align",
      "Visibility & lock",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 36 -------------------------------------------------------------- */
  {
    id: "acad-arch-drawing-revision",
    name: "Drawing Revision Automation",
    slug: "acad-arch-drawing-revision",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Revised drawings compared, changes clouded and tagged.",
    description:
      "Revised drawings compared, changes clouded and tagged.",
    what: [
      "What it runs through, in order: overlay versions, find changes, cloud & tag, log.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Overlay versions",
      "Find changes",
      "Cloud & tag",
      "Log",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 37 -------------------------------------------------------------- */
  {
    id: "acad-arch-cad-standards-checking",
    name: "CAD Standards Checking",
    slug: "acad-arch-cad-standards-checking",
    disciplines: ["architecture"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Wrong layers, blocks, text, dims and linetypes found and fixed.",
    description:
      "Wrong layers, blocks, text, dims and linetypes found and fixed.",
    what: [
      "What it runs through, in order: load standards, check, fix, report.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Load standards",
      "Check",
      "Fix",
      "Report",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },
];

/**
 * The cards, in the order they appear on the hub: Revit first, then AutoCAD,
 * each in the order they were drawn. The hub groups them by application and
 * numbers them off this array.
 */
export const architectureLineup: string[] = [
  "revit-arch-cad2rvt",
  "revit-arch-site-feasibility",
  "revit-arch-concept-design",
  "revit-arch-unit-planning",
  "revit-arch-area-calculation",
  "revit-arch-area-plan-generation",
  "revit-arch-schedule",
  "revit-arch-parking-mobility",
  "revit-arch-ramp-staircase",
  "revit-arch-ceiling-generation",
  "revit-arch-detailed-design",
  "revit-arch-parameter",
  "revit-arch-clash-detection",
  "revit-arch-interior-shop-drawing",
  "revit-arch-toilet-shop-drawing",
  "revit-arch-kitchen-shop-drawing",
  "revit-arch-ceiling-shop-drawing",
  "revit-arch-drywall-shop-drawing",
  "revit-arch-wardrobe-shop-drawing",
  "revit-arch-as-built",
  "revit-arch-view-sheet-generation",
  "revit-arch-pdf-dwg-exporter",
  "revit-arch-nwf-nwd-nwc-ifc-exporter",
  "revit-arch-scan-to-bim",
  "revit-arch-auto-dimensioning-tagging",
  "acad-arch-pdf-dwg-exporter",
  "acad-arch-layer-standardization",
  "acad-arch-batch-drawing-cleanup",
  "acad-arch-auto-dimensioning-tagging",
  "acad-arch-drawing-annotation",
  "acad-arch-elevation-section-update",
  "acad-arch-area-quantity-extraction",
  "acad-arch-schedule-extraction",
  "acad-arch-sheet-layout",
  "acad-arch-viewport-scale",
  "acad-arch-drawing-revision",
  "acad-arch-cad-standards-checking",
];
