import type { ToolSeed } from "./shared";

/**
 * Mep — 41 products: 25 Revit add-ins and 16 for AutoCAD.
 *
 * Generated by scripts/build-catalogue.mjs from the cards in cards/ — do not
 * edit. Every name, sentence and step comes off the card that shows it, so the
 * page and the animation can never drift apart. The one hand-written input is
 * scripts/summaries.json, which holds the supplied product descriptions.
 *
 * A tool that exists for both applications is two products here, because it is
 * two products: different work, different card, different add-in.
 */
export const mepTools: ToolSeed[] = [
  /* 1 --------------------------------------------------------------- */
  {
    id: "revit-mep-cad-to-revit",
    name: "CAD to Revit Automation",
    slug: "revit-mep-cad-to-revit",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically convert structural CAD drawings into Revit models, reducing manual modelling time.",
    description:
      "MEP CAD turned into Revit ducts, pipes, trays and fittings.",
    what: [
      "What it runs through, in order: link the dwg, read the layers, ducts, pipes & trays, fittings & risers.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Link the DWG",
      "Read the layers",
      "Ducts, pipes & trays",
      "Fittings & risers",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 2 --------------------------------------------------------------- */
  {
    id: "revit-mep-pdf-dwg-exporter",
    name: "PDF & DWG Exporter",
    slug: "revit-mep-pdf-dwg-exporter",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Export up to 300 sheets to PDF and DWG in just five minutes, directly from Revit.",
    description:
      "Hundreds of sheets to PDF and DWG in minutes, from Revit.",
    what: [
      "What it runs through, in order: select sheets, formats & naming, batch export, organised output.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Select sheets",
      "Formats & naming",
      "Batch export",
      "Organised output",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 3 --------------------------------------------------------------- */
  {
    id: "revit-mep-nwf-nwd-nwc-ifc-exporter",
    name: "NWF, NWD, NWC & IFC Exporter",
    slug: "revit-mep-nwf-nwd-nwc-ifc-exporter",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically export NWF, NWD, NWC, IFC, and other coordination files for seamless project coordination.",
    description:
      "Models exported to NWC and IFC, then combined into NWF and NWD.",
    what: [
      "What it runs through, in order: pick models, export nwc & ifc, build nwf, publish nwd.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick models",
      "Export NWC & IFC",
      "Build NWF",
      "Publish NWD",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 4 --------------------------------------------------------------- */
  {
    id: "revit-mep-scan-to-bim",
    name: "Scan-to-BIM Automation",
    slug: "revit-mep-scan-to-bim",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically convert point-cloud scans into accurate, structured Revit models.",
    description:
      "Point-cloud scans turned into Revit ducts, pipes and equipment.",
    what: [
      "What it runs through, in order: load the scan, ducts, pipes & trays, equipment.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Load the scan",
      "Ducts",
      "Pipes & trays",
      "Equipment",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 5 --------------------------------------------------------------- */
  {
    id: "revit-mep-grid-level",
    name: "Grid & Level Automation",
    slug: "revit-mep-grid-level",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Copies grids and levels from the ARCH/STR links, monitors them, and flags and fixes changes.",
    description:
      "Grids and levels copied from linked models and kept in sync.",
    what: [
      "What it runs through, in order: pick the links, copy & monitor, detect changes, update.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick the links",
      "Copy & monitor",
      "Detect changes",
      "Update",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 6 --------------------------------------------------------------- */
  {
    id: "revit-mep-schematic-design",
    name: "Schematic Design Automation",
    slug: "revit-mep-schematic-design",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Riser schematic with water, drainage and chilled water systems across all levels.",
    description:
      "Riser schematics and system connections drawn from your systems.",
    what: [
      "What it runs through, in order: levels, risers, equipment & branches, connections.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Levels",
      "Risers",
      "Equipment & branches",
      "Connections",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 7 --------------------------------------------------------------- */
  {
    id: "revit-mep-hvac-design",
    name: "HVAC Design Automation",
    slug: "revit-mep-hvac-design",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Room loads, then airflow, then AHU, then duct routing and sizing, then index-run pressure drop.",
    description:
      "Loads, airflows, AHU, duct routing, sizing and pressure drop.",
    what: [
      "What it runs through, in order: heat loads, airflow & equipment, route & size ducts, pressure drop.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Heat loads",
      "Airflow & equipment",
      "Route & size ducts",
      "Pressure drop",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 8 --------------------------------------------------------------- */
  {
    id: "revit-mep-equipment-placement",
    name: "Equipment Placement Automation",
    slug: "revit-mep-equipment-placement",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Equipment placed at predefined spots, with service clearances checked and resolved.",
    description:
      "Equipment placed at set locations, clearances checked and fixed.",
    what: [
      "What it runs through, in order: predefined locations, place equipment, check clearances, resolve & connect.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Predefined locations",
      "Place equipment",
      "Check clearances",
      "Resolve & connect",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 9 --------------------------------------------------------------- */
  {
    id: "revit-mep-pipe-routing",
    name: "Pipe Routing Automation",
    slug: "revit-mep-pipe-routing",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "CHW mains and branches, sized by flow, with velocity and pressure-drop checks.",
    description:
      "Pipe mains and branches routed, sized by flow and checked.",
    what: [
      "What it runs through, in order: terminals & flows, route mains & branches, size pipes, pressure drop.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Terminals & flows",
      "Route mains & branches",
      "Size pipes",
      "Pressure drop",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 10 -------------------------------------------------------------- */
  {
    id: "revit-mep-plumbing-drainage",
    name: "Plumbing & Drainage Automation",
    slug: "revit-mep-plumbing-drainage",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Gravity drainage with slopes, stacks and vents, sized by fixture units.",
    description:
      "Gravity drainage with slopes, stacks and vents, fully sized.",
    what: [
      "What it runs through, in order: fixtures, sloped branches, stacks & vents, drain to manhole.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Fixtures",
      "Sloped branches",
      "Stacks & vents",
      "Drain to manhole",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 11 -------------------------------------------------------------- */
  {
    id: "revit-mep-cable-tray-conduit",
    name: "Cable Tray & Conduit Automation",
    slug: "revit-mep-cable-tray-conduit",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Tray and conduit routes from the MDB to boards, with tray sized by fill.",
    description:
      "Tray and conduit routes to every board, sized by cable fill.",
    what: [
      "What it runs through, in order: loads & cables, route trays, conduits, size & fill.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Loads & cables",
      "Route trays",
      "Conduits",
      "Size & fill",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 12 -------------------------------------------------------------- */
  {
    id: "revit-mep-electrical-layout",
    name: "Electrical Layout Automation",
    slug: "revit-mep-electrical-layout",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Lights to a lux target, sockets, DB and circuits, with cable, breaker and voltage-drop checks.",
    description:
      "Lights, sockets and circuits, with cables sized and checked.",
    what: [
      "What it runs through, in order: lighting, power, circuits, size & check.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Lighting",
      "Power",
      "Circuits",
      "Size & check",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 13 -------------------------------------------------------------- */
  {
    id: "revit-mep-panel-schedule",
    name: "Panel Schedule Automation",
    slug: "revit-mep-panel-schedule",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Panel schedules built from circuits, with loads and phase balancing.",
    description:
      "Panel schedules from circuits, with loads and phase balance.",
    what: [
      "What it runs through, in order: read circuits, build schedule, balance phases, update.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Read circuits",
      "Build schedule",
      "Balance phases",
      "Update",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 14 -------------------------------------------------------------- */
  {
    id: "revit-mep-firefighting-sprinkler",
    name: "Firefighting / Sprinkler Automation",
    slug: "revit-mep-firefighting-sprinkler",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Heads by coverage, pipe routing, remote area and hydraulic calc.",
    description:
      "Sprinklers by coverage, piped and hydraulically calculated.",
    what: [
      "What it runs through, in order: place heads, route pipes, remote area, hydraulic calc.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Place heads",
      "Route pipes",
      "Remote area",
      "Hydraulic calc",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 15 -------------------------------------------------------------- */
  {
    id: "revit-mep-fire-alarm-layout",
    name: "Fire Alarm Layout Automation",
    slug: "revit-mep-fire-alarm-layout",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Detectors by coverage (with gap check), call points, sounders and loop to the panel.",
    description:
      "Detectors, call points and sounders placed by coverage, looped.",
    what: [
      "What it runs through, in order: detectors, coverage check, call points & sounders, loop wiring.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Detectors",
      "Coverage check",
      "Call points & sounders",
      "Loop wiring",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 16 -------------------------------------------------------------- */
  {
    id: "revit-mep-hangers-supports",
    name: "Hangers & Supports Automation",
    slug: "revit-mep-hangers-supports",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Hangers along ducts, pipes and trays at set spacing, anchored to the slab.",
    description:
      "Hangers along every service at set spacing, fixed to structure.",
    what: [
      "What it runs through, in order: pick services, ducts, pipes & trays, fix to structure.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick services",
      "Ducts",
      "Pipes & trays",
      "Fix to structure",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 17 -------------------------------------------------------------- */
  {
    id: "revit-mep-builders-work",
    name: "Builders Work Automation",
    slug: "revit-mep-builders-work",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically place sleeves, openings, and cutouts in structural elements based on coordinated MEP requirements.",
    description:
      "Sleeves, openings and cut-outs through structure and walls.",
    what: [
      "What it runs through, in order: read the services, find crossings, place sleeves, openings & cut-outs.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Read the services",
      "Find crossings",
      "Place sleeves",
      "Openings & cut-outs",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 18 -------------------------------------------------------------- */
  {
    id: "revit-mep-auto-dimensioning-tagging",
    name: "Auto Dimensioning & Tagging",
    slug: "revit-mep-auto-dimensioning-tagging",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically add dimensions between walls, interior elements, and lighting fixtures while intelligently positioning tags.",
    description:
      "Services dimensioned and tagged, equipment tags on any side.",
    what: [
      "What it runs through, in order: service dimensions, size & level tags, equipment tags, align to any side.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Service dimensions",
      "Size & level tags",
      "Equipment tags",
      "Align to any side",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 19 -------------------------------------------------------------- */
  {
    id: "revit-mep-clash-detection",
    name: "MEP Coordination & Clash Detection Automation",
    slug: "revit-mep-clash-detection",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "planned",
    summary:
      "MEP checked against STR and ARCH in a 3D clash view with clickable flags.",
    description:
      "MEP checked against STR and ARCH, a flag at every clash.",
    what: [
      "What it runs through, in order: pick disciplines, run the check, 3d clash view, click a flag.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick disciplines",
      "Run the check",
      "3D clash view",
      "Click a flag",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 20 -------------------------------------------------------------- */
  {
    id: "revit-mep-shop-drawing",
    name: "MEP Shop Drawing Automation",
    slug: "revit-mep-shop-drawing",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "planned",
    summary:
      "Layouts, sections, details and dimensions for MEP services.",
    description:
      "Layouts, sections, details and dimensions for MEP services.",
    what: [
      "What it runs through, in order: hvac layout, piping layout, sections, details.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "HVAC layout",
      "Piping layout",
      "Sections",
      "Details",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 21 -------------------------------------------------------------- */
  {
    id: "revit-mep-fabrication-spooling",
    name: "Fabrication & Spooling Automation",
    slug: "revit-mep-fabrication-spooling",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "planned",
    summary:
      "Pipe and duct runs split into spools, with spool sheets.",
    description:
      "Pipe runs split into spools, with welds and spool sheets.",
    what: [
      "What it runs through, in order: pick the run, split into spools, welds & fittings, spool sheets.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick the run",
      "Split into spools",
      "Welds & fittings",
      "Spool sheets",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 22 -------------------------------------------------------------- */
  {
    id: "revit-mep-schedule",
    name: "MEP Schedule Automation",
    slug: "revit-mep-schedule",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "planned",
    summary:
      "Schedules for equipment, fixtures, ducts, pipes and fittings.",
    description:
      "Export to Excel, edit there, push the changes back to Revit.",
    what: [
      "What it runs through, in order: pick schedules, export to excel, edit in excel, push back to revit.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick schedules",
      "Export to Excel",
      "Edit in Excel",
      "Push back to Revit",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 23 -------------------------------------------------------------- */
  {
    id: "revit-mep-parameter",
    name: "Parameter Automation",
    slug: "revit-mep-parameter",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "planned",
    summary:
      "Automatically create, rename, update, and manage Revit parameters and project data, even inside linked models.",
    description:
      "Create, rename and fill MEP parameters, even in linked models.",
    what: [
      "What it runs through, in order: define parameters, create & rename, fill values, update linked models.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Define parameters",
      "Create & rename",
      "Fill values",
      "Update linked models",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 24 -------------------------------------------------------------- */
  {
    id: "revit-mep-as-built",
    name: "MEP As-Built Drawing Automation",
    slug: "revit-mep-as-built",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "planned",
    summary:
      "MEP drawings updated from the final model and stamped AS-BUILT.",
    description:
      "MEP drawings updated from the final model and stamped AS-BUILT.",
    what: [
      "What it runs through, in order: final model in, update views & tags, stamp as-built, set ready.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Final model in",
      "Update views & tags",
      "Stamp AS-BUILT",
      "Set ready",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 25 -------------------------------------------------------------- */
  {
    id: "revit-mep-view-sheet-generation",
    name: "Automatic View & Sheet Generation",
    slug: "revit-mep-view-sheet-generation",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "planned",
    summary:
      "Automatically generate views and sheets, and place the views on the sheets in an organized layout.",
    description:
      "MEP views per level, placed on sheets in an organised layout.",
    what: [
      "What it runs through, in order: pick levels & templates, create views, create sheets, place views.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick levels & templates",
      "Create views",
      "Create sheets",
      "Place views",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 26 -------------------------------------------------------------- */
  {
    id: "acad-mep-pdf-dwg-exporter",
    name: "PDF & DWG Exporter",
    slug: "acad-mep-pdf-dwg-exporter",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Hundreds of CAD layouts batch-exported to standard PDF and DWG.",
    description:
      "Hundreds of CAD layouts batch-exported to standard PDF and DWG.",
    what: [
      "What it runs through, in order: pick drawings, page setup, batch export, named & filed.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick drawings",
      "Page setup",
      "Batch export",
      "Named & filed",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 27 -------------------------------------------------------------- */
  {
    id: "acad-mep-layer-standardization",
    name: "Layer Standardization",
    slug: "acad-mep-layer-standardization",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "New drawings matched to your template's layers and properties.",
    description:
      "New drawings matched to your template's layers and properties.",
    what: [
      "What it runs through, in order: load template, map layers, apply properties, whole set.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Load template",
      "Map layers",
      "Apply properties",
      "Whole set",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 28 -------------------------------------------------------------- */
  {
    id: "acad-mep-batch-drawing-cleanup",
    name: "Batch Drawing Cleanup",
    slug: "acad-mep-batch-drawing-cleanup",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Duplicates, unused layers, strays and errors removed in batch.",
    description:
      "Duplicates, unused layers, strays and errors removed in batch.",
    what: [
      "What it runs through, in order: scan drawings, overkill, purge & audit, whole set.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Scan drawings",
      "Overkill",
      "Purge & audit",
      "Whole set",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 29 -------------------------------------------------------------- */
  {
    id: "acad-mep-auto-dimensioning-tagging",
    name: "Auto Dimensioning & Tagging",
    slug: "acad-mep-auto-dimensioning-tagging",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Services dimensioned and tagged the same way on every drawing.",
    description:
      "Services dimensioned and tagged the same way on every drawing.",
    what: [
      "What it runs through, in order: pick rules, dimensions, tags, whole set.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick rules",
      "Dimensions",
      "Tags",
      "Whole set",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 30 -------------------------------------------------------------- */
  {
    id: "acad-mep-drawing-annotation",
    name: "Drawing Annotation Automation",
    slug: "acad-mep-drawing-annotation",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Notes, labels, callouts and symbols placed by your rules.",
    description:
      "Notes, labels, callouts and symbols placed by your rules.",
    what: [
      "What it runs through, in order: room labels, service notes, callouts, symbols.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Room labels",
      "Service notes",
      "Callouts",
      "Symbols",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 31 -------------------------------------------------------------- */
  {
    id: "acad-mep-elevation-section-update",
    name: "Elevation & Section Update Automation",
    slug: "acad-mep-elevation-section-update",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "MEP sections and elevations updated when plans change.",
    description:
      "MEP sections and elevations updated when plans change.",
    what: [
      "What it runs through, in order: detect plan change, update sections, update elevations, linked sheets.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Detect plan change",
      "Update sections",
      "Update elevations",
      "Linked sheets",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 32 -------------------------------------------------------------- */
  {
    id: "acad-mep-area-quantity-extraction",
    name: "Area & Quantity Extraction",
    slug: "acad-mep-area-quantity-extraction",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Duct, pipe and tray lengths and equipment counts from drawings.",
    description:
      "Duct, pipe and tray lengths and equipment counts from drawings.",
    what: [
      "What it runs through, in order: pick drawings, measure runs, count items, export.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick drawings",
      "Measure runs",
      "Count items",
      "Export",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 33 -------------------------------------------------------------- */
  {
    id: "acad-mep-schedule-extraction",
    name: "Schedule Extraction Automation",
    slug: "acad-mep-schedule-extraction",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Equipment, fixture, duct and pipe schedules pulled into Excel.",
    description:
      "Equipment, fixture, duct and pipe schedules pulled into Excel.",
    what: [
      "What it runs through, in order: read drawings, equipment & fixtures, ducts & pipes, export.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Read drawings",
      "Equipment & fixtures",
      "Ducts & pipes",
      "Export",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 34 -------------------------------------------------------------- */
  {
    id: "acad-mep-sheet-layout",
    name: "Sheet & Layout Automation",
    slug: "acad-mep-sheet-layout",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Layouts, title blocks, numbers, revisions and viewports.",
    description:
      "Layouts, title blocks, numbers, revisions and viewports.",
    what: [
      "What it runs through, in order: create layouts, title blocks, viewports, revisions.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Create layouts",
      "Title blocks",
      "Viewports",
      "Revisions",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 35 -------------------------------------------------------------- */
  {
    id: "acad-mep-viewport-scale",
    name: "Viewport & Scale Automation",
    slug: "acad-mep-viewport-scale",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Viewport scales, orientation and positions made consistent.",
    description:
      "Viewport scales, orientation and positions made consistent.",
    what: [
      "What it runs through, in order: scan sheets, set scale, align, visibility & lock.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Scan sheets",
      "Set scale",
      "Align",
      "Visibility & lock",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 36 -------------------------------------------------------------- */
  {
    id: "acad-mep-drawing-revision",
    name: "Drawing Revision Automation",
    slug: "acad-mep-drawing-revision",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Revised drawings compared, changes clouded and tagged.",
    description:
      "Revised drawings compared, changes clouded and tagged.",
    what: [
      "What it runs through, in order: overlay versions, find changes, cloud & tag, log.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Overlay versions",
      "Find changes",
      "Cloud & tag",
      "Log",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 37 -------------------------------------------------------------- */
  {
    id: "acad-mep-cad-standards-checking",
    name: "CAD Standards Checking",
    slug: "acad-mep-cad-standards-checking",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Wrong layers, blocks, text, dims and linetypes found and fixed.",
    description:
      "Wrong layers, blocks, text, dims and linetypes found and fixed.",
    what: [
      "What it runs through, in order: load standards, check, fix, report.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Load standards",
      "Check",
      "Fix",
      "Report",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 38 -------------------------------------------------------------- */
  {
    id: "acad-mep-mep-routing",
    name: "MEP Routing Automation",
    slug: "acad-mep-mep-routing",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Pipe, duct, tray and conduit routes drawn by your routing rules.",
    description:
      "Pipe, duct, tray and conduit routes drawn by your routing rules.",
    what: [
      "What it runs through, in order: mains, trays, pipes, branches.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Mains",
      "Trays",
      "Pipes",
      "Branches",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 39 -------------------------------------------------------------- */
  {
    id: "acad-mep-mep-equipment-layout",
    name: "MEP Equipment Layout Automation",
    slug: "acad-mep-mep-equipment-layout",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Equipment, fixtures and service points placed by your rules.",
    description:
      "Equipment, fixtures and service points placed by your rules.",
    what: [
      "What it runs through, in order: equipment, fixtures, service points, every room.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Equipment",
      "Fixtures",
      "Service points",
      "Every room",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 40 -------------------------------------------------------------- */
  {
    id: "acad-mep-mep-schematic",
    name: "MEP Schematic Generation",
    slug: "acad-mep-mep-schematic",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Riser and system schematics generated from the drawings.",
    description:
      "Riser and system schematics generated from the drawings.",
    what: [
      "What it runs through, in order: read plans, levels, connections, labels.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Read plans",
      "Levels",
      "Connections",
      "Labels",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 41 -------------------------------------------------------------- */
  {
    id: "acad-mep-mep-coordination",
    name: "MEP Coordination Automation",
    slug: "acad-mep-mep-coordination",
    disciplines: ["mep"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Overlapping services and clearance issues found between systems.",
    description:
      "Overlapping services and clearance issues found between systems.",
    what: [
      "What it runs through, in order: read levels, find crossings, check clashes, report.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Read levels",
      "Find crossings",
      "Check clashes",
      "Report",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },
];

/**
 * The cards, in the order they appear on the hub: Revit first, then AutoCAD,
 * each in the order they were drawn. The hub groups them by application and
 * numbers them off this array.
 */
export const mepLineup: string[] = [
  "revit-mep-cad-to-revit",
  "revit-mep-pdf-dwg-exporter",
  "revit-mep-nwf-nwd-nwc-ifc-exporter",
  "revit-mep-scan-to-bim",
  "revit-mep-grid-level",
  "revit-mep-schematic-design",
  "revit-mep-hvac-design",
  "revit-mep-equipment-placement",
  "revit-mep-pipe-routing",
  "revit-mep-plumbing-drainage",
  "revit-mep-cable-tray-conduit",
  "revit-mep-electrical-layout",
  "revit-mep-panel-schedule",
  "revit-mep-firefighting-sprinkler",
  "revit-mep-fire-alarm-layout",
  "revit-mep-hangers-supports",
  "revit-mep-builders-work",
  "revit-mep-auto-dimensioning-tagging",
  "revit-mep-clash-detection",
  "revit-mep-shop-drawing",
  "revit-mep-fabrication-spooling",
  "revit-mep-schedule",
  "revit-mep-parameter",
  "revit-mep-as-built",
  "revit-mep-view-sheet-generation",
  "acad-mep-pdf-dwg-exporter",
  "acad-mep-layer-standardization",
  "acad-mep-batch-drawing-cleanup",
  "acad-mep-auto-dimensioning-tagging",
  "acad-mep-drawing-annotation",
  "acad-mep-elevation-section-update",
  "acad-mep-area-quantity-extraction",
  "acad-mep-schedule-extraction",
  "acad-mep-sheet-layout",
  "acad-mep-viewport-scale",
  "acad-mep-drawing-revision",
  "acad-mep-cad-standards-checking",
  "acad-mep-mep-routing",
  "acad-mep-mep-equipment-layout",
  "acad-mep-mep-schematic",
  "acad-mep-mep-coordination",
];
