import type { ToolSeed } from "./shared";

/**
 * Structure — 34 products: 18 Revit add-ins and 16 for AutoCAD.
 *
 * Generated by scripts/build-catalogue.mjs from the cards in cards/ — do not
 * edit. Every name, sentence and step comes off the card that shows it, so the
 * page and the animation can never drift apart. The one hand-written input is
 * scripts/summaries.json, which holds the supplied product descriptions.
 *
 * A tool that exists for both applications is two products here, because it is
 * two products: different work, different card, different add-in.
 */
export const structureTools: ToolSeed[] = [
  /* 1 --------------------------------------------------------------- */
  {
    id: "revit-str-cad-to-revit",
    name: "CAD to Revit Automation",
    slug: "revit-str-cad-to-revit",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically convert structural CAD drawings into Revit models, reducing manual modelling time.",
    description:
      "Structural CAD turned into Revit columns, beams, walls, slabs.",
    what: [
      "What it runs through, in order: link the dwg, columns, beams & walls, slabs.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Link the DWG",
      "Columns",
      "Beams & walls",
      "Slabs",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 2 --------------------------------------------------------------- */
  {
    id: "revit-str-pdf-dwg-exporter",
    name: "PDF & DWG Exporter",
    slug: "revit-str-pdf-dwg-exporter",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Export up to 300 sheets to PDF and DWG in just five minutes, directly from Revit.",
    description:
      "Hundreds of sheets to PDF and DWG in minutes, from Revit.",
    what: [
      "What it runs through, in order: select sheets, formats & naming, batch export, organised output.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Select sheets",
      "Formats & naming",
      "Batch export",
      "Organised output",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 3 --------------------------------------------------------------- */
  {
    id: "revit-str-nwf-nwd-nwc-ifc-exporter",
    name: "NWF, NWD, NWC & IFC Exporter",
    slug: "revit-str-nwf-nwd-nwc-ifc-exporter",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically export NWF, NWD, NWC, IFC, and other coordination files for seamless project coordination.",
    description:
      "Models exported to NWC and IFC, then combined into NWF and NWD.",
    what: [
      "What it runs through, in order: pick models, export nwc & ifc, build nwf, publish nwd.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick models",
      "Export NWC & IFC",
      "Build NWF",
      "Publish NWD",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 4 --------------------------------------------------------------- */
  {
    id: "revit-str-scan-to-bim",
    name: "Scan-to-BIM Automation",
    slug: "revit-str-scan-to-bim",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically convert point-cloud scans into accurate, structured Revit models.",
    description:
      "Point-cloud scans turned into Revit columns, beams and slabs.",
    what: [
      "What it runs through, in order: load the scan, columns, beams & walls, slabs.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Load the scan",
      "Columns",
      "Beams & walls",
      "Slabs",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 5 --------------------------------------------------------------- */
  {
    id: "revit-str-grid",
    name: "Grid Automation",
    slug: "revit-str-grid",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically generate structural grids and levels based on project requirements.",
    description:
      "Grids built through your columns, even when unevenly placed.",
    what: [
      "What it runs through, in order: read the columns, align within tolerance, create grids, dimensions & levels.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Read the columns",
      "Align within tolerance",
      "Create grids",
      "Dimensions & levels",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 6 --------------------------------------------------------------- */
  {
    id: "revit-str-slab-design",
    name: "Slab Design Automation",
    slug: "revit-str-slab-design",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically generate slab layouts, slab types, levels, openings, and structural information.",
    description:
      "Slab layouts, types, levels and openings with structural data.",
    what: [
      "What it runs through, in order: slab layout, slab types, levels, openings.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Slab layout",
      "Slab types",
      "Levels",
      "Openings",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 7 --------------------------------------------------------------- */
  {
    id: "revit-str-staircase",
    name: "Staircase Automation",
    slug: "revit-str-staircase",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically generate staircases with appropriate levels, dimensions, supports, and structural elements.",
    description:
      "Concrete stairs between levels, with supports and dimensions.",
    what: [
      "What it runs through, in order: levels & parameters, flights & landing, supports, dimensions.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Levels & parameters",
      "Flights & landing",
      "Supports",
      "Dimensions",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 8 --------------------------------------------------------------- */
  {
    id: "revit-str-ramp",
    name: "Ramp Automation",
    slug: "revit-str-ramp",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically generate ramps based on levels, slopes, dimensions, and project requirements.",
    description:
      "Ramps from levels, slope and size, with supports and upstands.",
    what: [
      "What it runs through, in order: levels & slope, ramp slab, supports, edges.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Levels & slope",
      "Ramp slab",
      "Supports",
      "Edges",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 9 --------------------------------------------------------------- */
  {
    id: "revit-str-detailed-design",
    name: "Detailed Design Automation",
    slug: "revit-str-detailed-design",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automate repetitive detailing for doors, windows, curtain walls, kitchens, toilets, joinery, and finishes.",
    description:
      "Detail views for columns, beams, slabs, walls and footings.",
    what: [
      "What it runs through, in order: columns, beams, slabs & walls, foundations.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Columns",
      "Beams",
      "Slabs & walls",
      "Foundations",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 10 -------------------------------------------------------------- */
  {
    id: "revit-str-auto-dimensioning-tagging",
    name: "Auto Dimensioning & Tagging",
    slug: "revit-str-auto-dimensioning-tagging",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically add dimensions between walls, interior elements, and lighting fixtures while intelligently positioning tags.",
    description:
      "Grid and element dims, tags aligned on the side you choose.",
    what: [
      "What it runs through, in order: grid dimensions, element dimensions, tags, align to any side.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Grid dimensions",
      "Element dimensions",
      "Tags",
      "Align to any side",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 11 -------------------------------------------------------------- */
  {
    id: "revit-str-shop-drawing",
    name: "Shop Drawing Automation",
    slug: "revit-str-shop-drawing",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically create shop drawings including plans, sections, details, concrete dimensions, and associated documentation.",
    description:
      "Plans, sections, details and concrete dims, as annotated views.",
    what: [
      "What it runs through, in order: framing plan, sections, details, concrete dimensions.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Framing plan",
      "Sections",
      "Details",
      "Concrete dimensions",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 12 -------------------------------------------------------------- */
  {
    id: "revit-str-foundation-shop-drawing",
    name: "Foundation Shop Drawing Automation",
    slug: "revit-str-foundation-shop-drawing",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically create foundation shop drawings including footing layouts, concrete dimensions, levels, and associated documentation.",
    description:
      "Footing layouts, setting-out, levels and marks, as views.",
    what: [
      "What it runs through, in order: footing layout, setting-out, sections & levels, footing marks.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Footing layout",
      "Setting-out",
      "Sections & levels",
      "Footing marks",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 13 -------------------------------------------------------------- */
  {
    id: "revit-str-wall-shop-drawing",
    name: "Wall Shop Drawing Automation",
    slug: "revit-str-wall-shop-drawing",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically create wall shop drawings including openings, concrete dimensions, sections, and associated documentation.",
    description:
      "Wall elevations, openings and sections, fully dimensioned.",
    what: [
      "What it runs through, in order: wall elevation, wall plan, section, opening details.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Wall elevation",
      "Wall plan",
      "Section",
      "Opening details",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 14 -------------------------------------------------------------- */
  {
    id: "revit-str-builders-work",
    name: "Builders Work Automation",
    slug: "revit-str-builders-work",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically place sleeves, openings, and cutouts in structural elements based on coordinated MEP requirements.",
    description:
      "Sleeves, openings and cut-outs placed from coordinated MEP.",
    what: [
      "What it runs through, in order: read the mep, find crossings, place sleeves, openings & cut-outs.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Read the MEP",
      "Find crossings",
      "Place sleeves",
      "Openings & cut-outs",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 15 -------------------------------------------------------------- */
  {
    id: "revit-str-clash-detection",
    name: "Coordination & Clash Detection Automation",
    slug: "revit-str-clash-detection",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically create a 3D clash view inside Revit, with each clash marked by a flag that can be clicked to view its details.",
    description:
      "Structure checked against ARCH and MEP in a 3D clash view.",
    what: [
      "What it runs through, in order: structure vs others, run the check, 3d clash view, click a flag.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Structure vs others",
      "Run the check",
      "3D clash view",
      "Click a flag",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 16 -------------------------------------------------------------- */
  {
    id: "revit-str-schedule",
    name: "Schedule Automation",
    slug: "revit-str-schedule",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically create and update Revit schedules from model information.",
    description:
      "Export to Excel, edit there, push the changes back to Revit.",
    what: [
      "What it runs through, in order: pick schedules, export to excel, edit in excel, push back to revit.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick schedules",
      "Export to Excel",
      "Edit in Excel",
      "Push back to Revit",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 17 -------------------------------------------------------------- */
  {
    id: "revit-str-as-built",
    name: "As-Built Drawing Automation",
    slug: "revit-str-as-built",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically generate accurate as-built drawings from the final BIM model.",
    description:
      "Drawings updated from the final model and stamped AS-BUILT.",
    what: [
      "What it runs through, in order: final model in, update views & tags, stamp as-built, set ready.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Final model in",
      "Update views & tags",
      "Stamp AS-BUILT",
      "Set ready",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 18 -------------------------------------------------------------- */
  {
    id: "revit-str-view-sheet-generation",
    name: "Automatic View & Sheet Generation",
    slug: "revit-str-view-sheet-generation",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["revit"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Automatically generate views and sheets, and place the views on the sheets in an organized layout.",
    description:
      "Views per level, placed on sheets in an organised layout.",
    what: [
      "What it runs through, in order: pick levels & templates, create views, create sheets, place views.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick levels & templates",
      "Create views",
      "Create sheets",
      "Place views",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 19 -------------------------------------------------------------- */
  {
    id: "acad-str-pdf-dwg-exporter",
    name: "PDF & DWG Exporter",
    slug: "acad-str-pdf-dwg-exporter",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Hundreds of CAD layouts batch-exported to standard PDF and DWG.",
    description:
      "Hundreds of CAD layouts batch-exported to standard PDF and DWG.",
    what: [
      "What it runs through, in order: pick drawings, page setup, batch export, named & filed.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick drawings",
      "Page setup",
      "Batch export",
      "Named & filed",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 20 -------------------------------------------------------------- */
  {
    id: "acad-str-layer-standardization",
    name: "Layer Standardization",
    slug: "acad-str-layer-standardization",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "New drawings matched to your template's layers and properties.",
    description:
      "New drawings matched to your template's layers and properties.",
    what: [
      "What it runs through, in order: load template, map layers, apply properties, whole set.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Load template",
      "Map layers",
      "Apply properties",
      "Whole set",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 21 -------------------------------------------------------------- */
  {
    id: "acad-str-batch-drawing-cleanup",
    name: "Batch Drawing Cleanup",
    slug: "acad-str-batch-drawing-cleanup",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Duplicates, unused layers, strays and errors removed in batch.",
    description:
      "Duplicates, unused layers, strays and errors removed in batch.",
    what: [
      "What it runs through, in order: scan drawings, overkill, purge & audit, whole set.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Scan drawings",
      "Overkill",
      "Purge & audit",
      "Whole set",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 22 -------------------------------------------------------------- */
  {
    id: "acad-str-auto-dimensioning-tagging",
    name: "Auto Dimensioning & Tagging",
    slug: "acad-str-auto-dimensioning-tagging",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Grid, column and beam dims and tags, the same on every drawing.",
    description:
      "Grid, column and beam dims and tags, the same on every drawing.",
    what: [
      "What it runs through, in order: pick rules, dimensions, tags, whole set.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick rules",
      "Dimensions",
      "Tags",
      "Whole set",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 23 -------------------------------------------------------------- */
  {
    id: "acad-str-drawing-annotation",
    name: "Drawing Annotation Automation",
    slug: "acad-str-drawing-annotation",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Notes, labels, callouts and symbols placed by your rules.",
    description:
      "Notes, labels, callouts and symbols placed by your rules.",
    what: [
      "What it runs through, in order: slab marks, member notes, callouts, symbols.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Slab marks",
      "Member notes",
      "Callouts",
      "Symbols",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 24 -------------------------------------------------------------- */
  {
    id: "acad-str-elevation-section-update",
    name: "Elevation & Section Update Automation",
    slug: "acad-str-elevation-section-update",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Structural elevations and sections updated when plans change.",
    description:
      "Structural elevations and sections updated when plans change.",
    what: [
      "What it runs through, in order: detect plan change, update elevations, update sections, linked sheets.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Detect plan change",
      "Update elevations",
      "Update sections",
      "Linked sheets",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 25 -------------------------------------------------------------- */
  {
    id: "acad-str-area-quantity-extraction",
    name: "Area & Quantity Extraction",
    slug: "acad-str-area-quantity-extraction",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Member counts, sizes and concrete quantities from many drawings.",
    description:
      "Member counts, sizes and concrete quantities from many drawings.",
    what: [
      "What it runs through, in order: pick drawings, count members, measure, export.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Pick drawings",
      "Count members",
      "Measure",
      "Export",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 26 -------------------------------------------------------------- */
  {
    id: "acad-str-schedule-extraction",
    name: "Schedule Extraction Automation",
    slug: "acad-str-schedule-extraction",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Column, beam, slab, foundation and rebar data pulled into Excel.",
    description:
      "Column, beam, slab, foundation and rebar data pulled into Excel.",
    what: [
      "What it runs through, in order: read drawings, members, reinforcement, export.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Read drawings",
      "Members",
      "Reinforcement",
      "Export",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 27 -------------------------------------------------------------- */
  {
    id: "acad-str-sheet-layout",
    name: "Sheet & Layout Automation",
    slug: "acad-str-sheet-layout",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Layouts, title blocks, numbers, revisions and viewports.",
    description:
      "Layouts, title blocks, numbers, revisions and viewports.",
    what: [
      "What it runs through, in order: create layouts, title blocks, viewports, revisions.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Create layouts",
      "Title blocks",
      "Viewports",
      "Revisions",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 28 -------------------------------------------------------------- */
  {
    id: "acad-str-viewport-scale",
    name: "Viewport & Scale Automation",
    slug: "acad-str-viewport-scale",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Viewport scales, orientation and positions made consistent.",
    description:
      "Viewport scales, orientation and positions made consistent.",
    what: [
      "What it runs through, in order: scan sheets, set scale, align, visibility & lock.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Scan sheets",
      "Set scale",
      "Align",
      "Visibility & lock",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 29 -------------------------------------------------------------- */
  {
    id: "acad-str-drawing-revision",
    name: "Drawing Revision Automation",
    slug: "acad-str-drawing-revision",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Revised drawings compared, changes clouded and tagged.",
    description:
      "Revised drawings compared, changes clouded and tagged.",
    what: [
      "What it runs through, in order: overlay versions, find changes, cloud & tag, log.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Overlay versions",
      "Find changes",
      "Cloud & tag",
      "Log",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 30 -------------------------------------------------------------- */
  {
    id: "acad-str-cad-standards-checking",
    name: "CAD Standards Checking",
    slug: "acad-str-cad-standards-checking",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Wrong layers, blocks, text, dims and linetypes found and fixed.",
    description:
      "Wrong layers, blocks, text, dims and linetypes found and fixed.",
    what: [
      "What it runs through, in order: load standards, check, fix, report.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Load standards",
      "Check",
      "Fix",
      "Report",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 31 -------------------------------------------------------------- */
  {
    id: "acad-str-structural-detail",
    name: "Structural Detail Automation",
    slug: "acad-str-structural-detail",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Repetitive connection, section, foundation and standard details.",
    description:
      "Repetitive connection, section, foundation and standard details.",
    what: [
      "What it runs through, in order: connections, sections, foundations, standard details.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Connections",
      "Sections",
      "Foundations",
      "Standard details",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 32 -------------------------------------------------------------- */
  {
    id: "acad-str-foundation-drawing",
    name: "Foundation Drawing Automation",
    slug: "acad-str-foundation-drawing",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Footing, pedestal and foundation drawings from parameters.",
    description:
      "Footing, pedestal and foundation drawings from parameters.",
    what: [
      "What it runs through, in order: parameters, plan, section & levels, next type.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Parameters",
      "Plan",
      "Section & levels",
      "Next type",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 33 -------------------------------------------------------------- */
  {
    id: "acad-str-bar-bending-schedule",
    name: "Bar Bending Schedule Generation",
    slug: "acad-str-bar-bending-schedule",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "BBS generated and updated from your reinforcement drawings.",
    description:
      "BBS generated and updated from your reinforcement drawings.",
    what: [
      "What it runs through, in order: read callouts, shapes & lengths, weights, update.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Read callouts",
      "Shapes & lengths",
      "Weights",
      "Update",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },

  /* 34 -------------------------------------------------------------- */
  {
    id: "acad-str-structural-schedule",
    name: "Structural Schedule Automation",
    slug: "acad-str-structural-schedule",
    disciplines: ["structure"],
    group: "documentation",
    stage: "documentation",
    software: ["autocad"],
    glyph: "layers",
    mockup: "viewer",
    status: "available",
    summary:
      "Schedules kept in the drawing, linked and auto-updated.",
    description:
      "Schedules kept in the drawing, linked and auto-updated.",
    what: [
      "What it runs through, in order: place table, link members, detect change, auto-update.",
      "Every one of those is a step somebody does by hand today, on every drawing of every job.",
    ],
    features: [
      "Place table",
      "Link members",
      "Detect change",
      "Auto-update",
    ],
    inputs: ["Project model or drawing set", "The office standard it follows"],
    outputs: ["The work, done", "A log of what it produced"],
  },
];

/**
 * The cards, in the order they appear on the hub: Revit first, then AutoCAD,
 * each in the order they were drawn. The hub groups them by application and
 * numbers them off this array.
 */
export const structureLineup: string[] = [
  "revit-str-cad-to-revit",
  "revit-str-pdf-dwg-exporter",
  "revit-str-nwf-nwd-nwc-ifc-exporter",
  "revit-str-scan-to-bim",
  "revit-str-grid",
  "revit-str-slab-design",
  "revit-str-staircase",
  "revit-str-ramp",
  "revit-str-detailed-design",
  "revit-str-auto-dimensioning-tagging",
  "revit-str-shop-drawing",
  "revit-str-foundation-shop-drawing",
  "revit-str-wall-shop-drawing",
  "revit-str-builders-work",
  "revit-str-clash-detection",
  "revit-str-schedule",
  "revit-str-as-built",
  "revit-str-view-sheet-generation",
  "acad-str-pdf-dwg-exporter",
  "acad-str-layer-standardization",
  "acad-str-batch-drawing-cleanup",
  "acad-str-auto-dimensioning-tagging",
  "acad-str-drawing-annotation",
  "acad-str-elevation-section-update",
  "acad-str-area-quantity-extraction",
  "acad-str-schedule-extraction",
  "acad-str-sheet-layout",
  "acad-str-viewport-scale",
  "acad-str-drawing-revision",
  "acad-str-cad-standards-checking",
  "acad-str-structural-detail",
  "acad-str-foundation-drawing",
  "acad-str-bar-bending-schedule",
  "acad-str-structural-schedule",
];
