/**
 * Turn the designed tool cards into modules the site can render.
 *
 * Each card in `cards/<discipline>/` is a finished, self-contained piece of
 * design: a fixed 1280-wide stage, and a script that drives every moving part
 * of it off one number between 0 and 100. Rewriting either half by hand would
 * only be a chance to get one of a few hundred nodes wrong, so neither is
 * rewritten — this pulls the markup and the value function out verbatim and
 * emits them as a module. `CardScene` supplies the clock.
 *
 * Run it whenever a card is added or redrawn:
 *
 *   node scripts/build-cards.mjs
 *
 * The generated files are committed, so a build never depends on this having
 * been run; this is only how they are refreshed.
 */

import { existsSync, readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, basename } from "node:path";

const CARDS_DIR = "cards";
const OUT_DIR = join("src", "components", "marketplace", "cards");

/**
 * Where the cards live, and how a card becomes a tool id.
 *
 * cards/<software>/<discipline>/NN-name.html, and the id is derived from that
 * path — the same derivation scripts/build-catalogue.mjs uses, so the cards
 * and the catalogue cannot disagree about what a tool is called. A card with
 * no matching tool is still emitted; the site simply never asks for it.
 */
const SOFTWARE = ["revit", "autocad"];
const DISCIPLINES = ["architecture", "structure", "mep"];
const SHORT = { architecture: "arch", structure: "str", mep: "mep" };

function toolIdFor(software, discipline, file) {
  const slug = basename(file, ".html").replace(/^\d+-/, "");
  return `${software === "revit" ? "revit" : "acad"}-${SHORT[discipline]}-${slug}`;
}

/* ------------------------------------------------------------------ */
/* Vendor logos                                                        */
/*                                                                     */
/* The cards say what they plug into, and the vendor half of that wants */
/* the vendor's own mark rather than their name set in our typeface.    */
/* Those are trademarks, so the files come from the vendor and are      */
/* dropped into public/logos; nothing here draws an approximation of    */
/* one. Until a file is there the card falls back to type.              */
/*                                                                     */
/* Resolved here rather than at runtime because this has to be safe to  */
/* import from a client component, and reading the filesystem is not.   */
/* ------------------------------------------------------------------ */

const VENDOR_FILES = {
  Autodesk: "/logos/autodesk.png",
  Microsoft: "/logos/microsoft.png",
  Trimble: "/logos/trimble.png",
  Bentley: "/logos/bentley.png",
  Oracle: "/logos/oracle.png",
  Graphisoft: "/logos/graphisoft.png",
};

function emitVendorLogos() {
  const found = Object.entries(VENDOR_FILES).filter(([, path]) =>
    existsSync(join("public", path)),
  );
  writeFileSync(
    join("src", "data", "vendor-logos.ts"),
    `/**
 * Vendor marks that are actually on file.
 *
 * Generated by scripts/build-cards.mjs — do not edit. Drop a vendor PNG into
 * public/logos (autodesk.png, microsoft.png, …) and run the script again; the
 * cards pick it up and stop falling back to the wordmark set as type.
 */
export const VENDOR_LOGOS: Record<string, string> = {
${found.map(([vendor, path]) => `  ${JSON.stringify(vendor)}: ${JSON.stringify(path)},`).join("\n")}
};

export function vendorLogo(vendor?: string): string | undefined {
  return vendor ? VENDOR_LOGOS[vendor] : undefined;
}

export default VENDOR_LOGOS;
`,
  );
  console.log(`vendor logos on file: ${found.length ? found.map(([v]) => v).join(", ") : "none"}`);
}

/* ------------------------------------------------------------------ */
/* Adjustments made on the way out                                     */
/* ------------------------------------------------------------------ */

const BT = String.fromCharCode(96);
const BS = String.fromCharCode(92);

/**
 * Make a block of markup safe to sit inside a template literal.
 *
 * Backslashes first, or the escapes added after would be escaped in turn. The
 * cards are hand-built HTML and do contain backslashes — a Windows export path
 * in the exporter card, for one — so this is not theoretical.
 */
function escapeForTemplate(markup) {
  return markup
    .split(BS)
    .join(BS + BS)
    .split(BT)
    .join(BS + BT)
    .split("$" + "{")
    .join(BS + "$" + "{");
}

/**
 * Names the cards were drawn with, against the names they are sold under.
 *
 * A card is a finished design and its copy is not rewritten here — with one
 * exception: the name on the card has to be the name in the catalogue, or a
 * visitor reads one thing on the artwork and another on the back of the same
 * card. Site & Massing was drawn while it was still called Site & Feasibility;
 * the rest of that card, subhead included, is already about massing.
 *
 * Keyed by tool id so it survives the files being renumbered or redrawn, and
 * applied across the whole card: the add-in names its own ribbon panel inside
 * the mocked Revit session, and a card whose title says one thing while its
 * ribbon says another reads as a mistake.
 */
const PRODUCT_RENAMES = {};

function renameProduct(markup, toolId, label) {
  const rename = PRODUCT_RENAMES[toolId];
  if (!rename) return markup;
  const [from, to] = rename;
  if (!markup.includes(from)) {
    console.warn(`  ${label}: nothing says "${from}" any more — rename skipped`);
    return markup;
  }
  return markup.split(from).join(to);
}

/* ------------------------------------------------------------------ */
/* The add-in lockup                                                   */
/*                                                                     */
/* Every card ends in a bar saying what it plugs into, and the design   */
/* sets that as an orange rule with "Add-in for / Autodesk® Revit®"     */
/* beside it. The house cards use the vendor's own lockup instead — the */
/* Revit tile with the name next to it — and the two should not be      */
/* different things on the same page, so the designed cards are swapped */
/* over to it here rather than by hand in forty files that get redrawn. */
/*                                                                     */
/* Matched on the block's own contents rather than on where it sits.    */
/* ------------------------------------------------------------------ */

/**
 * The lockup, per application.
 *
 * A card ends in a bar saying what it plugs into, drawn as an orange rule with
 * "Add-in for / Autodesk® Revit®" beside it — or AutoCAD, on the AutoCAD
 * cards. The house cards use the vendor's own lockup instead: the product tile
 * with the name next to it. Those should not be two different things on the
 * same page, so the designed cards are swapped over here rather than by hand
 * in a hundred and twelve files that get redrawn.
 *
 * Matched on the block's own contents rather than on where it sits.
 */
const PRODUCTS = {
  Revit: { logo: "/logos/revit.png", label: "Revit" },
  AutoCAD: { logo: "/logos/autocad.png", label: "AutoCAD" },
};

/**
 * The drawn lockup, matched rather than quoted.
 *
 * It used to be compared as an exact string, which broke the day the cards
 * were redrawn: the Lite set is identical except that the orange rule is 32px
 * tall instead of 34px, and every one of the 112 cards silently kept the
 * design's own lockup instead of the site's. A pattern that lets the rule be
 * any height survives that, and says out loud which part is allowed to vary.
 */
const DRAWN_LOCKUP =
  /<div style="display: flex; align-items: center; gap: 14px;"><div style="width: 3px; height: \d+px; border-radius: 2px; background: #F28C28;"><\/div><div style="display: flex; flex-direction: column; gap: 2px;"><div style="font-size: 12px; color: #5A626E;">Add-in for<\/div><div style="font-family: Archivo, 'Arial Narrow', sans-serif; font-stretch: 88%; font-weight: 700; font-size: 18px; color: #172B4D;">Autodesk® (Revit|AutoCAD)®<\/div><\/div><\/div>/g;

/**
 * The lockup the site puts in its place: "Add-in for", a rule, the product's
 * own mark.
 *
 * The mark carries the product name better than setting it as type beside the
 * mark did — that repeated "Revit" twice, once as a logo and once as a word.
 * The name stays in the image's alt text, which is where a screen reader
 * wants it anyway.
 */
const houseLockup = (product) =>
  '<div style="display: flex; align-items: center; gap: 14px;">' +
  '<div style="font-size: 15px; font-weight: 600; letter-spacing: -0.1px; color: #16181C; white-space: nowrap;">Add-in for</div>' +
  '<div style="width: 1px; height: 30px; background: #D5D9DF;"></div>' +
  `<img src="${PRODUCTS[product].logo}" alt="Autodesk ${PRODUCTS[product].label}" width="34" height="34" style="display: block; width: 34px; height: 34px; object-fit: contain;">` +
  "</div>";

function swapLockup(markup, label) {
  let swapped = 0;
  const out = markup.replace(DRAWN_LOCKUP, (_, product) => {
    swapped += 1;
    return houseLockup(product);
  });
  if (!swapped) console.warn(`  ${label}: no add-in lockup to swap — left as drawn`);
  return out;
}

/* ------------------------------------------------------------------ */
/* The panel                                                           */
/* ------------------------------------------------------------------ */

/**
 * The card without its drawing.
 *
 * Every card is one flex row of two children: a 380px column carrying the
 * name, the line under it and the add-in row, and beside it the panel the
 * animation plays in. The panel comes out, so what is published is what the
 * tool is called and what it does — no mock of the application, no diagram of
 * how it works.
 *
 * Dropping it lets the card shrink from 1280 wide to the column plus the
 * stage's own padding, which is the whole point: the type is then rendered at
 * nearly full size instead of the third of it a 1280-wide card was scaled to.
 *
 * Every column is held at one height, so the add-in rows — pinned to
 * the bottom of their column — line up across a row of cards.
 */
const COLUMN = /<div style="width: 380px; flex-shrink: 0; height: (\d+)px;/;

/** The column, its padding, and the box they need. */
const COLUMN_WIDTH = 380;
const COLUMN_HEIGHT = 290;
const STAGE_WIDTH = COLUMN_WIDTH + 48 + 48;
const STAGE_HEIGHT = COLUMN_HEIGHT + 30 + 36;

function dropPanel(markup, label) {
  const at = markup.search(COLUMN);
  if (at < 0) {
    console.warn(`  ${label}: no text column found — left whole`);
    return markup;
  }

  // Walk to the tag that closes the column; everything after it is the panel.
  let depth = 0;
  let i = at;
  let end = -1;
  while (i < markup.length) {
    const open = markup.indexOf("<div", i);
    const close = markup.indexOf("</div>", i);
    if (close < 0) break;
    if (open >= 0 && open < close) {
      depth += 1;
      i = open + 4;
    } else {
      depth -= 1;
      i = close + 6;
      if (depth === 0) {
        end = i;
        break;
      }
    }
  }
  if (end < 0) {
    console.warn(`  ${label}: text column does not close — left whole`);
    return markup;
  }

  return markup
    .slice(at, end)
    .replace(COLUMN, `<div style="width: ${COLUMN_WIDTH}px; flex-shrink: 0; height: ${COLUMN_HEIGHT}px;`);
}

/* ------------------------------------------------------------------ */
/* The heading                                                         */
/* ------------------------------------------------------------------ */

/**
 * Every heading gets the same height, and nothing else is touched.
 *
 * This used to resize the type itself, on the assumption that the cards all
 * set their titles at 50px and the long ones needed stepping down. They do
 * not: the design sizes each one for its own name, from 50px for "Schedule"
 * down to 27px for "MEP Coordination & Clash Detection", and every one of
 * them is already fitted to two lines in the column. Re-deriving that from a
 * character count only undid it — short names were being *enlarged* to 50px,
 * which is why the cards no longer agreed with each other.
 *
 * So the size is the design's. All this does is hold the block at two lines
 * of the largest of them, so that the line under the heading and the add-in
 * row below it sit at the same height on every card in a row.
 */

/**
 * One title size for every card, matching the rest of the site.
 *
 * The designs set each title for its own name — 49px for "Schedule", 26px for
 * "MEP Coordination & Clash Detection" — which is right when a card is looked
 * at on its own and wrong the moment a hundred of them sit in a grid. Worse,
 * the stage scales to the card's width at very nearly 1:1, so a 49px title
 * arrived on screen at roughly twice the 24px the back of the same card sets
 * its heading at. Turning the card over changed the size of its own name.
 *
 * 26px is the floor of the measured set, which is what makes it the one size
 * that is safe to use flat: every name is already known to fit two lines at
 * it, so nothing overruns the column. Scaled into the card it lands at ~24px
 * — the `card-title-lg` step in tailwind.config.ts, which is where the rest
 * of the site's cards now get their headings from. Change both together.
 */
const CARD_TITLE_PX = 26;

/** Two lines at the size above, at the 1.0 leading the designs set. */
const HEADING_BLOCK = 56;

/**
 * The size each heading fits two lines at, measured in the browser.
 *
 * The design sizes every title for its own name, and for most of them that is
 * already two lines in a 380px column. A couple of dozen are not: once the
 * drawing came out and the card shrank to the column, names like "MEP
 * Coordination & Clash Detection" ran to three lines and four.
 *
 * These sizes come from measuring the rendered text in the real face — text
 * width scales linearly with size, so the largest size that fits is one
 * division away. Estimating it from a character count is what broke this
 * before: no per-character average survives condensed Archivo.
 *
 * Regenerate with scratchpad/sizes.cjs against a running build.
 */
const HEADING_SIZES = JSON.parse(readFileSync(join("scripts", "heading-sizes.json"), "utf8"));

/** The heading as the measurement saw it: tags gone, entities decoded. */
const headingKey = (inner) =>
  inner
    .replace(/<[^>]+>/g, "")
    .replace(/&amp;/g, "&")
    .replace(/&nbsp;/g, " ")
    .replace(/\s+/g, " ")
    .trim();

/**
 * Hold every heading to two lines, and every block to the same height.
 *
 * The size is the design's own unless it overruns the column, and the floor
 * under the block is what keeps the line below the heading — and the add-in
 * row under that — level across a row of cards.
 */
function fitHeading(markup, label) {
  const HEAD = /<h1 style="([^"]*)">([\s\S]*?)<\/h1>/;
  const found = markup.match(HEAD);
  if (!found) {
    console.warn(`  ${label}: no heading to align — left as drawn`);
    return markup;
  }

  const [whole, style, inner] = found;
  const declared = Number((style.match(/font-size:\s*([\d.]+)px/) ?? [, 0])[1]);
  const measured = HEADING_SIZES[headingKey(inner)];
  // The house size, unless this particular name was measured as needing to be
  // smaller still to hold two lines. In practice the measured floor *is* the
  // house size, so this is a guard rather than a source of variation.
  const fits = measured && declared ? Math.min(declared, measured) : declared;
  const size = Math.min(fits || CARD_TITLE_PX, CARD_TITLE_PX);

  const fitted = (size ? style.replace(/font-size:\s*[\d.]+px/, `font-size: ${size}px`) : style)
    .concat(` min-height: ${HEADING_BLOCK}px;`);

  return markup.replace(whole, `<h1 style="${fitted}">${inner}</h1>`);
}

/* ------------------------------------------------------------------ */
/* Extraction                                                          */
/* ------------------------------------------------------------------ */

/** `style="a: b; c: d"` → a React style object, as source text. */
function styleToObject(css) {
  const entries = css
    .split(";")
    .map((rule) => rule.trim())
    .filter(Boolean)
    .map((rule) => {
      const at = rule.indexOf(":");
      const property = rule.slice(0, at).trim();
      const value = rule.slice(at + 1).trim();
      const key = property.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
      return `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`;
    });
  return `{\n${entries.join("\n")}\n}`;
}

/**
 * Give every driven attribute a valid starting value.
 *
 * A card authors these empty — cx="" — and fills them on the first frame. That
 * is fine once the scene is running, but the browser parses the markup before
 * then and complains about every one of them. Seeding a zero costs nothing:
 * the node is transparent until the frame that gives it a real value.
 */
const ATTR_SEED = {
  d: "M0 0",
  fill: "none",
  stroke: "none",
};

/**
 * Seeded by attribute, not by where the attribute sits.
 *
 * This used to look for `r="" data-bind-r=` as one string, which only worked
 * because the cards happened to emit the plain attribute immediately before
 * its binding. The Lite set sorts every element's attributes alphabetically,
 * so `data-bind-r` now comes first and the pair never met — and 112 cards
 * shipped with `r=""`, which the browser rejects as an invalid length.
 *
 * An empty value is invalid for every attribute a card drives, so any empty
 * one belongs to a binding and can be seeded on sight.
 */
function seedAttrs(markup, attrs) {
  let out = markup;
  for (const attr of attrs) {
    // A length wants a number; a path wants a moveto; a paint wants a paint.
    const seed = ATTR_SEED[attr] ?? "0";
    out = out.split(` ${attr}=""`).join(` ${attr}="${seed}"`);
  }
  return out;
}

function extract(path, label, toolId) {
  const html = readFileSync(path, "utf8");
  const lines = html.split(/\r?\n/);

  // ---- the stage, and everything inside it -------------------------
  const stageLine = lines.findIndex((line) => line.includes('class="bimac-stage"'));
  if (stageLine < 0) throw new Error(`${label}: no .bimac-stage`);
  const sectionEnd = lines.findIndex((line) => line.trim() === "</section>");
  if (sectionEnd < 0) throw new Error(`${label}: no closing </section>`);

  const styleMatch = lines[stageLine].match(/style="([^"]*)"/);
  if (!styleMatch) throw new Error(`${label}: stage has no style`);

  // The stage is rebuilt rather than patched.
  //
  // The cards do not agree on how they frame themselves: most are a padded
  // flex row holding the text column beside the drawing, but some are an
  // unpadded column with the padding on a wrapper inside. Keeping each card's
  // own stage was fine while the whole of it shipped; now that only the text
  // column does, a card of the second kind loses the padding with the wrapper
  // and sits flush against its own border.
  //
  // So every card gets the same frame, and only its colours are carried over.
  const original = styleMatch[1];
  const carry = (property, fallback) =>
    // Anchored, so `color` is not read out of `background-color`.
    (original.match(new RegExp(`(?:^|;)\\s*${property}:\\s*([^;]+)`)) ?? [, fallback])[1].trim();

  const style = [
    `width: ${STAGE_WIDTH}px`,
    `height: ${STAGE_HEIGHT}px`,
    "box-sizing: border-box",
    "padding: 30px 48px 36px 48px",
    "display: flex",
    `background-color: ${carry("background-color", "#FFFFFF")}`,
    `color: ${carry("color", "#16181C")}`,
    "overflow: hidden",
  ].join("; ");

  // The line before </section> closes the stage, so the stage's own children
  // run from the line after it to the line before that.
  // Which attributes this card drives. The design lists them itself, and the
  // list differs per card — most drive none, a few drive d, r, cx or fill.
  const attrsMatch = html.match(/var ATTRS = (\[[^\]]*\])/);
  const attrs = attrsMatch ? JSON.parse(attrsMatch[1]) : [];

  const raw = lines.slice(stageLine + 1, sectionEnd - 1).join("\n");
  const markup = seedAttrs(
    dropPanel(fitHeading(swapLockup(renameProduct(raw, toolId, label), label), label), label),
    attrs,
  );
  if (!markup.trim()) throw new Error(`${label}: empty stage`);

  // ---- the value function, verbatim --------------------------------
  const from = html.indexOf("renderVals() {");
  if (from < 0) throw new Error(`${label}: no renderVals`);
  const to = html.indexOf("\n}\n", from);
  if (to < 0) throw new Error(`${label}: renderVals does not close`);
  let body = html.slice(from + "renderVals() {".length, to);

  // Its only tie to the class it came from is where it reads the clock.
  const readsClock = "var p = (this.state && typeof this.state.p === 'number') ? this.state.p : 88;";
  if (!body.includes(readsClock)) throw new Error(`${label}: unexpected renderVals preamble`);
  body = body.replace(readsClock, "// p is the argument.");

  // ---- the loop length ---------------------------------------------
  const loop = html.match(/% (1[0-9]000)\)/);
  if (!loop) throw new Error(`${label}: cannot find the loop length`);

  // Which attributes this card drives. The design lists them itself, and the
  const title = (html.match(/<title>([^<]*)<\/title>/) ?? [, label])[1];

  return {
    style,
    markup,
    body,
    loopMs: Number(loop[1]),
    attrs,
    title,
    // The design's own box was 1280x616 around a drawing that is no longer
    // there. What ships is the column and the padding that framed it.
    width: STAGE_WIDTH,
    height: STAGE_HEIGHT,
  };
}

function emit(moduleName, toolId, card) {
  const source = `/* eslint-disable */
// @ts-nocheck
/**
 * ${card.title}
 *
 * Generated by scripts/build-cards.mjs — do not edit. Both halves come out of
 * the design verbatim: \`markup\` is its stage, and \`values\` is its own
 * renderVals, untouched apart from taking the clock as an argument instead of
 * reading it off a component. See the script for the few things it adjusts.
 */

export const id = ${JSON.stringify(toolId)};
export const title = ${JSON.stringify(card.title)};
export const width = ${card.width};
export const height = ${card.height};
export const loopMs = ${card.loopMs};

/**
 * The attributes this card drives, as the design lists them.
 *
 * Each bound node carries data-bind-<attr> holding a template like "[[wx]]",
 * which the scene fills from the frame's values.
 */
export const attrs = ${JSON.stringify(card.attrs)};

/** The stage's own styles, off the design's root element. */
export const stage = ${styleToObject(card.style)};

export const markup = ${BT}
${escapeForTemplate(card.markup)}
${BT};

/** Everything the markup binds to, for one position in the loop. */
export function values(p) {${card.body}}

const card = { id, title, width, height, loopMs, attrs, stage, markup, values };
export default card;
`;
  writeFileSync(join(OUT_DIR, `${moduleName}.ts`), source);
}

/* ------------------------------------------------------------------ */

mkdirSync(OUT_DIR, { recursive: true });
emitVendorLogos();

const emitted = [];

for (const software of SOFTWARE) {
  for (const discipline of DISCIPLINES) {
    const dir = join(CARDS_DIR, software, discipline);
    if (!existsSync(dir)) continue;

    const files = readdirSync(dir)
      .filter((f) => f.endsWith(".html"))
      .sort();

    for (const file of files) {
      const toolId = toolIdFor(software, discipline, file);
      const label = `${software}/${discipline}/${file}`;
      const card = extract(join(dir, file), label, toolId);
      const moduleName = `${software}-${discipline}-${basename(file, ".html")}`;
      emit(moduleName, toolId, card);
      emitted.push({ software, discipline, toolId, moduleName });
    }
    console.log(`${software}/${discipline}`.padEnd(24) + `${files.length} card(s)`);
  }
}

/* ---- the two indexes the site imports ------------------------------ */

writeFileSync(
  join(OUT_DIR, "ids.ts"),
  `/**
 * Which tools ship a designed card, and nothing else about them.
 *
 * Generated by scripts/build-cards.mjs — do not edit. Kept apart from the
 * cards themselves so the server side can ask the question without pulling
 * every card into its bundle, and so the card modules stay client-only: they
 * export functions, and a function cannot cross into a client component as a
 * prop.
 */
export const DESIGNED_CARD_IDS = new Set<string>([
${emitted.map((e) => `  ${JSON.stringify(e.toolId)},`).join("\n")}
]);

export default DESIGNED_CARD_IDS;
`,
);

writeFileSync(
  join(OUT_DIR, "index.ts"),
  `"use client";

/**
 * The tools that ship a designed card of their own.
 *
 * Generated by scripts/build-cards.mjs — do not edit. Add a card to
 * cards/<discipline>/, map its file to a tool id in that script, and run it
 * again.
 */
import type { DesignedCard } from "../CardScene";
${emitted.map((e, i) => `import card${i} from "./${e.moduleName}";`).join("\n")}

export const DESIGNED_CARDS: Record<string, DesignedCard> = {
${emitted.map((e, i) => `  ${JSON.stringify(e.toolId)}: card${i},`).join("\n")}
};

export default DESIGNED_CARDS;
`,
);

console.log(`\n${emitted.length} card(s) emitted to ${OUT_DIR}`);
