/**
 * Turn the designed tool cards into modules the site can render.
 *
 * Each card in `cards/<discipline>/` is a finished, self-contained piece of
 * design: a fixed 1280-wide stage, and a script that drives every moving part
 * of it off one number between 0 and 100. Rewriting either half by hand would
 * only be a chance to get one of a few hundred nodes wrong, so neither is
 * rewritten — this pulls the markup and the value function out verbatim and
 * emits them as a module. `CardScene` supplies the clock.
 *
 * Run it whenever a card is added or redrawn:
 *
 *   node scripts/build-cards.mjs
 *
 * The generated files are committed, so a build never depends on this having
 * been run; this is only how they are refreshed.
 */

import { existsSync, readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, basename } from "node:path";

const CARDS_DIR = "cards";
const OUT_DIR = join("src", "components", "marketplace", "cards");

/**
 * Where the cards live, and how a card becomes a tool id.
 *
 * cards/<software>/<discipline>/NN-name.html, and the id is derived from that
 * path — the same derivation scripts/build-catalogue.mjs uses, so the cards
 * and the catalogue cannot disagree about what a tool is called. A card with
 * no matching tool is still emitted; the site simply never asks for it.
 */
const SOFTWARE = ["revit", "autocad"];
const DISCIPLINES = ["architecture", "structure", "mep"];
const SHORT = { architecture: "arch", structure: "str", mep: "mep" };

function toolIdFor(software, discipline, file) {
  const slug = basename(file, ".html").replace(/^\d+-/, "");
  return `${software === "revit" ? "revit" : "acad"}-${SHORT[discipline]}-${slug}`;
}

/* ------------------------------------------------------------------ */
/* Vendor logos                                                        */
/*                                                                     */
/* The cards say what they plug into, and the vendor half of that wants */
/* the vendor's own mark rather than their name set in our typeface.    */
/* Those are trademarks, so the files come from the vendor and are      */
/* dropped into public/logos; nothing here draws an approximation of    */
/* one. Until a file is there the card falls back to type.              */
/*                                                                     */
/* Resolved here rather than at runtime because this has to be safe to  */
/* import from a client component, and reading the filesystem is not.   */
/* ------------------------------------------------------------------ */

const VENDOR_FILES = {
  Autodesk: "/logos/autodesk.png",
  Microsoft: "/logos/microsoft.png",
  Trimble: "/logos/trimble.png",
  Bentley: "/logos/bentley.png",
  Oracle: "/logos/oracle.png",
  Graphisoft: "/logos/graphisoft.png",
};

function emitVendorLogos() {
  const found = Object.entries(VENDOR_FILES).filter(([, path]) =>
    existsSync(join("public", path)),
  );
  writeFileSync(
    join("src", "data", "vendor-logos.ts"),
    `/**
 * Vendor marks that are actually on file.
 *
 * Generated by scripts/build-cards.mjs — do not edit. Drop a vendor PNG into
 * public/logos (autodesk.png, microsoft.png, …) and run the script again; the
 * cards pick it up and stop falling back to the wordmark set as type.
 */
export const VENDOR_LOGOS: Record<string, string> = {
${found.map(([vendor, path]) => `  ${JSON.stringify(vendor)}: ${JSON.stringify(path)},`).join("\n")}
};

export function vendorLogo(vendor?: string): string | undefined {
  return vendor ? VENDOR_LOGOS[vendor] : undefined;
}

export default VENDOR_LOGOS;
`,
  );
  console.log(`vendor logos on file: ${found.length ? found.map(([v]) => v).join(", ") : "none"}`);
}

/* ------------------------------------------------------------------ */
/* Adjustments made on the way out                                     */
/* ------------------------------------------------------------------ */

const BT = String.fromCharCode(96);
const BS = String.fromCharCode(92);

/**
 * Make a block of markup safe to sit inside a template literal.
 *
 * Backslashes first, or the escapes added after would be escaped in turn. The
 * cards are hand-built HTML and do contain backslashes — a Windows export path
 * in the exporter card, for one — so this is not theoretical.
 */
function escapeForTemplate(markup) {
  return markup
    .split(BS)
    .join(BS + BS)
    .split(BT)
    .join(BS + BT)
    .split("$" + "{")
    .join(BS + "$" + "{");
}

/**
 * Names the cards were drawn with, against the names they are sold under.
 *
 * A card is a finished design and its copy is not rewritten here — with one
 * exception: the name on the card has to be the name in the catalogue, or a
 * visitor reads one thing on the artwork and another on the back of the same
 * card. Site & Massing was drawn while it was still called Site & Feasibility;
 * the rest of that card, subhead included, is already about massing.
 *
 * Keyed by tool id so it survives the files being renumbered or redrawn, and
 * applied across the whole card: the add-in names its own ribbon panel inside
 * the mocked Revit session, and a card whose title says one thing while its
 * ribbon says another reads as a mistake.
 */
const PRODUCT_RENAMES = {};

function renameProduct(markup, toolId, label) {
  const rename = PRODUCT_RENAMES[toolId];
  if (!rename) return markup;
  const [from, to] = rename;
  if (!markup.includes(from)) {
    console.warn(`  ${label}: nothing says "${from}" any more — rename skipped`);
    return markup;
  }
  return markup.split(from).join(to);
}

/* ------------------------------------------------------------------ */
/* The add-in lockup                                                   */
/*                                                                     */
/* Every card ends in a bar saying what it plugs into, and the design   */
/* sets that as an orange rule with "Add-in for / Autodesk® Revit®"     */
/* beside it. The house cards use the vendor's own lockup instead — the */
/* Revit tile with the name next to it — and the two should not be      */
/* different things on the same page, so the designed cards are swapped */
/* over to it here rather than by hand in forty files that get redrawn. */
/*                                                                     */
/* Matched on the block's own contents rather than on where it sits.    */
/* ------------------------------------------------------------------ */

/**
 * The lockup, per application.
 *
 * A card ends in a bar saying what it plugs into, drawn as an orange rule with
 * "Add-in for / Autodesk® Revit®" beside it — or AutoCAD, on the AutoCAD
 * cards. The house cards use the vendor's own lockup instead: the product tile
 * with the name next to it. Those should not be two different things on the
 * same page, so the designed cards are swapped over here rather than by hand
 * in a hundred and twelve files that get redrawn.
 *
 * Matched on the block's own contents rather than on where it sits.
 */
const PRODUCTS = {
  Revit: { logo: "/logos/revit.png", label: "Revit" },
  AutoCAD: { logo: "/logos/autocad.png", label: "AutoCAD" },
};

const drawnLockup = (product) =>
  '<div style="display: flex; align-items: center; gap: 14px;">' +
  '<div style="width: 3px; height: 34px; border-radius: 2px; background: #F28C28;"></div>' +
  '<div style="display: flex; flex-direction: column; gap: 2px;">' +
  '<div style="font-size: 12px; color: #5A626E;">Add-in for</div>' +
  "<div style=\"font-family: Archivo, 'Arial Narrow', sans-serif; font-stretch: 88%; font-weight: 700; font-size: 18px; color: #172B4D;\">Autodesk® " +
  product +
  "®</div></div></div>";

const houseLockup = (product) =>
  '<div style="display: flex; align-items: center; gap: 14px;">' +
  `<div style="font-size: 15px; font-weight: 600; letter-spacing: -0.1px; color: #16181C; white-space: nowrap;">${PRODUCTS[product].label} Add-in</div>` +
  '<div style="width: 1px; height: 30px; background: #D5D9DF;"></div>' +
  `<img src="${PRODUCTS[product].logo}" alt="${PRODUCTS[product].label}" width="32" height="32" style="display: block; width: 32px; height: 32px; object-fit: contain;">` +
  '<div style="display: flex; flex-direction: column; gap: 1px; line-height: 1.05;">' +
  "<div style=\"font-family: Archivo, 'Arial Narrow', sans-serif; font-weight: 800; font-size: 15px; letter-spacing: 0.2px; color: #16181C;\">AUTODESK</div>" +
  `<div style="font-family: Archivo, 'Arial Narrow', sans-serif; font-weight: 500; font-size: 14px; color: #16181C;">${PRODUCTS[product].label}</div>` +
  "</div></div>";

function swapLockup(markup, label) {
  for (const product of Object.keys(PRODUCTS)) {
    const drawn = drawnLockup(product);
    if (markup.includes(drawn)) {
      return markup.split(drawn).join(houseLockup(product));
    }
  }
  console.warn(`  ${label}: no add-in lockup to swap — left as drawn`);
  return markup;
}

/* ------------------------------------------------------------------ */
/* The heading                                                         */
/*                                                                     */
/* Every card sets its title as "<name><br>Automation" at 50px, which   */
/* is two lines for a short name and three for a long one — and a card  */
/* whose heading runs to three lines pushes its step list down out of   */
/* line with the card beside it.                                        */
/*                                                                     */
/* So the hard break comes out and the name is allowed to wrap into the */
/* line "Automation" sits on, the block is held at exactly two lines'   */
/* height whatever it holds, and the type steps down only for the names */
/* too long to fit two lines at full size. Nothing measures text here,  */
/* so the steps are by character count and deliberately generous.       */
/* ------------------------------------------------------------------ */

/** Two lines at the size the cards are drawn at — what every heading takes. */
const HEADING_BLOCK = 106;

/**
 * The width one character takes, as a fraction of the font size.
 *
 * Measured off the rendered page, not guessed: "PDF & DWG Exporter" — 18
 * characters — comes out 404px wide at 50px, which is 0.449. Rounded up,
 * because a heading that is slightly small costs nothing and one that is
 * slightly wide is clipped.
 */
const CHAR_EM = 0.46;

/** How much of the 380px column the heading may use. */
const HEADING_WIDTH = 360;

/** Below this the type is too small to be a heading; wrap instead. */
const MIN_KEPT_SIZE = 36;

/** What fits on one line of the column at a given size. */
const fits = (chars) => Math.floor(HEADING_WIDTH / (chars * CHAR_EM));

/**
 * Size the heading so it fits the column.
 *
 * The design sets the title as two lines — the name, a <br>, then
 * "Automation" — and marks the name `white-space: nowrap` so it never breaks
 * mid-phrase. For most titles that is right and the type only has to step
 * down a little to fit.
 *
 * For the long ones it is not: holding "NWF, NWD, NWC & IFC Exporter" on one
 * unbreakable line means either clipping it or shrinking the heading to
 * something that is no longer a heading. Those give up the nowrap and the
 * break, and wrap across both lines instead.
 *
 * The block is held at two lines' height either way, so the step lists stay
 * level across a row.
 */
function fitHeading(markup, label) {
  const HEAD = /<h1 style="([^"]*)">([\s\S]*?)<\/h1>/;
  const found = markup.match(HEAD);
  if (!found) {
    console.warn(`  ${label}: no heading to fit — left as drawn`);
    return markup;
  }

  const [whole, style] = found;
  let inner = found[2];

  const plain = (html) =>
    html.replace(/<[^>]+>/g, "").replace(/&amp;/g, "&").replace(/\s+/g, " ").trim();

  const lines = inner.split("<br>").map(plain);
  const longest = lines.reduce((most, line) => Math.max(most, line.length), 0);

  let size = Math.min(50, fits(longest));
  if (size < MIN_KEPT_SIZE) {
    // Let it wrap: both lines' worth of width, shared across two lines.
    const total = lines.join(" ").length;
    size = Math.min(50, fits(total / 2));
    inner = inner
      .split("<br>")
      .join(" ")
      .split(' style="white-space: nowrap;"')
      .join("");
  }

  const lineHeight = 1.06;
  const fitted = style
    .replace(/font-size:\s*[\d.]+px/, `font-size: ${size}px`)
    .replace(/line-height:\s*[\d.]+/, `line-height: ${lineHeight}`)
    .concat(` min-height: ${HEADING_BLOCK}px;`);

  return markup.replace(whole, `<h1 style="${fitted}">${inner}</h1>`);
}

/* ------------------------------------------------------------------ */
/* Extraction                                                          */
/* ------------------------------------------------------------------ */

/** `style="a: b; c: d"` → a React style object, as source text. */
function styleToObject(css) {
  const entries = css
    .split(";")
    .map((rule) => rule.trim())
    .filter(Boolean)
    .map((rule) => {
      const at = rule.indexOf(":");
      const property = rule.slice(0, at).trim();
      const value = rule.slice(at + 1).trim();
      const key = property.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
      return `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`;
    });
  return `{\n${entries.join("\n")}\n}`;
}

/**
 * Give every driven attribute a valid starting value.
 *
 * A card authors these empty — cx="" — and fills them on the first frame. That
 * is fine once the scene is running, but the browser parses the markup before
 * then and complains about every one of them. Seeding a zero costs nothing:
 * the node is transparent until the frame that gives it a real value.
 */
const ATTR_SEED = {
  d: "M0 0",
  fill: "none",
  stroke: "none",
};

function seedAttrs(markup, attrs) {
  let out = markup;
  for (const attr of attrs) {
    // A length wants a number; a path wants a moveto; a paint wants a paint.
    const seed = ATTR_SEED[attr] ?? "0";
    out = out.split(` ${attr}="" data-bind-${attr}=`).join(` ${attr}="${seed}" data-bind-${attr}=`);
  }
  return out;
}

function extract(path, label, toolId) {
  const html = readFileSync(path, "utf8");
  const lines = html.split(/\r?\n/);

  // ---- the stage, and everything inside it -------------------------
  const stageLine = lines.findIndex((line) => line.includes('class="bimac-stage"'));
  if (stageLine < 0) throw new Error(`${label}: no .bimac-stage`);
  const sectionEnd = lines.findIndex((line) => line.trim() === "</section>");
  if (sectionEnd < 0) throw new Error(`${label}: no closing </section>`);

  const styleMatch = lines[stageLine].match(/style="([^"]*)"/);
  if (!styleMatch) throw new Error(`${label}: stage has no style`);
  const style = styleMatch[1];

  // The line before </section> closes the stage, so the stage's own children
  // run from the line after it to the line before that.
  // Which attributes this card drives. The design lists them itself, and the
  // list differs per card — most drive none, a few drive d, r, cx or fill.
  const attrsMatch = html.match(/var ATTRS = (\[[^\]]*\])/);
  const attrs = attrsMatch ? JSON.parse(attrsMatch[1]) : [];

  const raw = lines.slice(stageLine + 1, sectionEnd - 1).join("\n");
  const markup = seedAttrs(
    fitHeading(swapLockup(renameProduct(raw, toolId, label), label), label),
    attrs,
  );
  if (!markup.trim()) throw new Error(`${label}: empty stage`);

  // ---- the value function, verbatim --------------------------------
  const from = html.indexOf("renderVals() {");
  if (from < 0) throw new Error(`${label}: no renderVals`);
  const to = html.indexOf("\n}\n", from);
  if (to < 0) throw new Error(`${label}: renderVals does not close`);
  let body = html.slice(from + "renderVals() {".length, to);

  // Its only tie to the class it came from is where it reads the clock.
  const readsClock = "var p = (this.state && typeof this.state.p === 'number') ? this.state.p : 88;";
  if (!body.includes(readsClock)) throw new Error(`${label}: unexpected renderVals preamble`);
  body = body.replace(readsClock, "// p is the argument.");

  // ---- the loop length ---------------------------------------------
  const loop = html.match(/% (1[0-9]000)\)/);
  if (!loop) throw new Error(`${label}: cannot find the loop length`);

  // Which attributes this card drives. The design lists them itself, and the
  const title = (html.match(/<title>([^<]*)<\/title>/) ?? [, label])[1];

  return {
    style,
    markup,
    body,
    loopMs: Number(loop[1]),
    attrs,
    title,
    width: Number(style.match(/width:\s*(\d+)px/)[1]),
    height: Number(style.match(/height:\s*(\d+)px/)[1]),
  };
}

function emit(moduleName, toolId, card) {
  const source = `/* eslint-disable */
// @ts-nocheck
/**
 * ${card.title}
 *
 * Generated by scripts/build-cards.mjs — do not edit. Both halves come out of
 * the design verbatim: \`markup\` is its stage, and \`values\` is its own
 * renderVals, untouched apart from taking the clock as an argument instead of
 * reading it off a component. See the script for the few things it adjusts.
 */

export const id = ${JSON.stringify(toolId)};
export const title = ${JSON.stringify(card.title)};
export const width = ${card.width};
export const height = ${card.height};
export const loopMs = ${card.loopMs};

/**
 * The attributes this card drives, as the design lists them.
 *
 * Each bound node carries data-bind-<attr> holding a template like "[[wx]]",
 * which the scene fills from the frame's values.
 */
export const attrs = ${JSON.stringify(card.attrs)};

/** The stage's own styles, off the design's root element. */
export const stage = ${styleToObject(card.style)};

export const markup = ${BT}
${escapeForTemplate(card.markup)}
${BT};

/** Everything the markup binds to, for one position in the loop. */
export function values(p) {${card.body}}

const card = { id, title, width, height, loopMs, attrs, stage, markup, values };
export default card;
`;
  writeFileSync(join(OUT_DIR, `${moduleName}.ts`), source);
}

/* ------------------------------------------------------------------ */

mkdirSync(OUT_DIR, { recursive: true });
emitVendorLogos();

const emitted = [];

for (const software of SOFTWARE) {
  for (const discipline of DISCIPLINES) {
    const dir = join(CARDS_DIR, software, discipline);
    if (!existsSync(dir)) continue;

    const files = readdirSync(dir)
      .filter((f) => f.endsWith(".html"))
      .sort();

    for (const file of files) {
      const toolId = toolIdFor(software, discipline, file);
      const label = `${software}/${discipline}/${file}`;
      const card = extract(join(dir, file), label, toolId);
      const moduleName = `${software}-${discipline}-${basename(file, ".html")}`;
      emit(moduleName, toolId, card);
      emitted.push({ software, discipline, toolId, moduleName });
    }
    console.log(`${software}/${discipline}`.padEnd(24) + `${files.length} card(s)`);
  }
}

/* ---- the two indexes the site imports ------------------------------ */

writeFileSync(
  join(OUT_DIR, "ids.ts"),
  `/**
 * Which tools ship a designed card, and nothing else about them.
 *
 * Generated by scripts/build-cards.mjs — do not edit. Kept apart from the
 * cards themselves so the server side can ask the question without pulling
 * every card into its bundle, and so the card modules stay client-only: they
 * export functions, and a function cannot cross into a client component as a
 * prop.
 */
export const DESIGNED_CARD_IDS = new Set<string>([
${emitted.map((e) => `  ${JSON.stringify(e.toolId)},`).join("\n")}
]);

export default DESIGNED_CARD_IDS;
`,
);

writeFileSync(
  join(OUT_DIR, "index.ts"),
  `"use client";

/**
 * The tools that ship a designed card of their own.
 *
 * Generated by scripts/build-cards.mjs — do not edit. Add a card to
 * cards/<discipline>/, map its file to a tool id in that script, and run it
 * again.
 */
import type { DesignedCard } from "../CardScene";
${emitted.map((e, i) => `import card${i} from "./${e.moduleName}";`).join("\n")}

export const DESIGNED_CARDS: Record<string, DesignedCard> = {
${emitted.map((e, i) => `  ${JSON.stringify(e.toolId)}: card${i},`).join("\n")}
};

export default DESIGNED_CARDS;
`,
);

console.log(`\n${emitted.length} card(s) emitted to ${OUT_DIR}`);
